.travis.yml
This PR fixes the travis setup so that we'll install rust nightly properly and then build a python package and run tests with it.
=> Fix travis jobs

.travis.yml
This commit adds wheel building to the travis builds. It will only run
on tag pushes so the wheel uploads are done on when we push a release.
=> Add wheel builds to travis

.travis.yml
This commit adds CI configuration to run tests on osx too. retworkx
supports running on osx, linux, and windows yet it was only testing
linux and windows in ci which left osx potentially open to breaking
inadvertently. This should prevent that moving forward by verifying
that new changes run on osx too.
=> Add CI jobs for osx to travis config

tests/test_weakly_connected.py
This commit adds a new test module for verifying that the utility
function number_weakly_connected_components() works as expected.
=> Add tests to verify number_weakly_connected_components()

Cargo.toml, src/dag_isomorphism.rs, src/lib.rs, tests/test_edges.py
This commit migrates the internal graph representation of a PyDAG object
from daggy to use stabledigraph in petgraph directly. This removes an
abstraction layer from the stack and also makes it easier to use the dag
in python since the indexes are stable now. The implementation of the
petgraph traits is borrowed heavily from
https://github.com/mitchmindtree/daggy/pull/21 which added a stable
graph dag implementation to daggy. If/when daggy pushes a new release
that includes this implementation and keeps up to date with the latest
version of petgraph it will probably be worth switching back to that
newer version of daggy. But that can be decided when that happens.
Fixes #6
=> Remove daggy dependency and use StableGraph

docs/source/api.rst, src/lib.rs, tests/test_adj.py, tests/test_nodes.py
This commit adds 3 new methods to the PyDAG class to add equivalent
functionality to some networkx methods. The first two are in_edges and
out_edges. These functions are basically the same as adj_direction
except it's split by direction and also changes the output format to
be a list of tuples with node indexes and edge data. This way one can
reproduce/recreate the edges in the graph easily. The third method is
out_degree, which is the missing dual of in_degree but for the other
direction.
=> Add extra methods to PyDAG class

.travis.yml, appveyor.yml, tools/install_rust.sh
The latest 0.1.0 release failed the wheel builds on linux and windows. This was due
to changes in the cibuildwheel project for the 1.0.0 release . It now supports
building with both manylinux1 and manylinux2010. Manylinux2010 includes
a version of curl that no longer has the --proto option which is what
was used for downloading rustup as part of the build workflow. To
workaround this issue this commit switches to using wget which should do
the certificate checking without any extra arguments across all environments.
At the same time this bumps the cibuildwheel version to the latest across all jobs
=> Fix wheel builds

docs/source/api.rst, src/lib.rs, tests/test_ancestors_descendants.py, tests/test_depth.py
This commit adds 2 new methods for getting the list of ancestors and
descendants of a node.
=> Add PyDAG methods for ancestors and descendents

docs/source/api.rst, src/lib.rs, tests/test_nodes.py
This commit adds a function to retworkx that implements a
lexicographical topological sort for a PyDAG object. It takes in a
mandatory sort function that will take in a node's data and return a
string. This returned string is used as the key for sorting.
=> Add lexicographical topological sort function

src/lib.rs
A couple of utility functions, mainly *_edges() and *_degree were not
dealing with multigraphs correctly. This is because all these functions
were mistakenly dealing with nodes instead of edges. This would mean
results were missing or were undercounting in the case when there were
multiple edges between 2 nodes. This commit fixes this by switching to
use petgraph's edges_directed() method instead of the
neighbors_directed().
=> Fix issues with multigraphs

docs/source/api.rst, src/lib.rs, tests/test_deepcopy.py
This commit adds support for pickling and running copy.deepcopy() on
PyDAG objects. To do this 3 things are done, first it sets the module
for the class definition to be 'retworkx' instead of the default
builtins. Then it adds a `__getstate__` method to return a dictionary
that can be used reconstruct the contents of the graph and `__setstate__`
which takes in that dictionary and builds a new graph StableDiGraph
object from that. It's worth noting post a deepcopy() the node indices
may not be the same if there were any removals in the original PyDAG
object.
=> Add support for pickling/deepcopy on PyDAG

.travis.yml
This commit adds ci jobs for testing on non-x86 architectures. Non-x86
architectures will only run a single python 3.7 job. Now that the
manylinux2014 spec [1] exists we can start publishing wheels for non-x86
architectures. Adding test jobs is the first step towards that goal.
[1] https://www.python.org/dev/peps/pep-0599/
=> Add CI jobs for other architectures

src/lib.rs, tests/test_depth.py
Previously retworkx only exposed the dag_longest_path_length() function
which gave the pairwise length of the longest path. However, there are
some cases where that path needs to be exposed itself. This commit adds
a new function dag_longest_path() to address that use case which instead
of returning the pairwise length it returns a list of node indexes for
that path.
=> Add dag_longest_path function

src/lib.rs, tests/test_pred_succ.py
This commit adds a bfs_successors function that mirrors the same
function from networkx. It leverages petgraph's bfs visitor struct which
makes the implementation straightforward. There is an outerloop that
does the graph traversal using the Bfs struct and then an inner loop to
return all the children from that node.
=> Add bfs_successors function

src/lib.rs, tests/test_edges.py
This commit adds a new method to the PyDAG class, has_edge(). Like it's
name implies this method returns a boolean value, true if there is an
edge between the nodes specified, and false if there is not.
=> Add PyDAG.has_edge() method

.travis.yml
This commit adds a new job to compile and check rustfmt on new
submissions. This will make sure that we don't waste time on testing PRs
that don't compile or have formatting issues.
=> Add travis job to compile and run rustfmt

src/lib.rs, tests/test_pred_succ.py
There was a bug in the output from the successors and predecessors
methods for the PyDAG class with multigraphs. If there were multiple
edges to a node the output list would return the same node data twice.
This was unexpected because there is only one successor node not
multiple. To fix this issue this commit only adds a node to the output
of these methods once.
=> Don't add duplicates to successors or predecessors

src/lib.rs
This commit fixes a small oversight in the string comparison function
for the lexicographical topological sort function. In the fallback case
we incorrectly reversing the order of the comparison for the node ids.
This resulted in a reverse sort for keys that were the same.
=> Fix incorrect comparison ordering

docs/source/api.rst, src/lib.rs, tests/test_floyd_warshall.py
Returns `Dict[int, Dict[int, int]]` where keys are node *indices* and final value is distance. If a path does not exist, there is no entry in the returned dictionary. This is different from networkx, where `inf` fills the place of paths that don't exist.
I couldn't find a way to get `inf` returned :(
=> Implement floyd warshall: the shortest paths between every pair of nodes

src/lib.rs
In the recent few commits a couple of non-fatal compiler warnings
slipped through. This commit just goes through and corrects them so a
clean cargo build doesn't output any warnings.
=> Fix compiler warnings

docs/source/api.rst, src/lib.rs, tests/test_edges.py
Currently the PyDAG class always checks on add_edge() calls that the new
edge would not create a cycle in the dag. However, this comes at a
performance cost, and sometimes depending on the size and complexity of
the dag this can be large. To avoid this performance penalty by default
this commit changes the PyDAG class to not do this checking by default.
It adds a new attribute check_cycle to the class, if this is set to True
then cycle checking is enabled on subsequent calls to add_edge().
=> Make cycle checking opt-in

docs/source/api.rst, src/lib.rs, tests/test_layers.py
This commit adds a function to get layers from a PyDAG object. You
provide it with an inital set of indexes for the first layer and it will
return a list of lists with the node data, where each inner list
represents a layer.
=> Add layers function

docs/source/api.rst, src/lib.rs, tests/test_nodes.py
Currently the nodes() method returns a list of node data, but if for any
reason there is a need to get a list of all the indexes in use by the
PyDAG object the only option right now is to use a function like
topological sort which will return the sorted indexes. However, if
sorting isn't a requirement this is slower than needed. This commit adds
a method node_indexes() which will return a list of all node indexes.
=> Add PyDAG method to get node indexes

appveyor.yml
32 bit windows wheels were not added before because the 64bit msvc
and rustc compilers were being used and trying to link against 32 bit
python which would error. This commit fixes that by using 32 bit
compilers (which needs to be done in a separate job). Now at the next
release we will have win32 wheels built and published along with 64 bit
windows.
=> Add win32 wheel builds to release job

.travis.yml
This commit adds non-x86 wheel builds to the deploy stage right now it's
built using master of cibuildwheel because support for non-x86 hasn't
been released yet (but the dev version was used to build the currently
hosted non-x86 artifacts on pypi). When a release is available with the
missing support this will be updated in a follow up commit.
Additionally, the s390x support is left out because of an issue
installing rustup in clefos 7 (which is required per the manylinux
2014 spec). Once https://github.com/rust-lang/rustup/issues/2225 is
fixed or worked around this can be added.
=> Add non-x86 manylinux wheel builds to deploy stage

.travis.yml
Currently we were not building an sdist at release time and to enable
source installs from pypi we'd have to manually build and upload an
sdist. This commit corrects this by adding a CI job to the deploy stage
which will create an sdist and upload it to pypi.
=> Add sdist job

src/lib.rs, tests/test_ancestors_descendants.py
The previous implementation of the ancestors and descendants functions
were exceedingly inefficient. They iterated over each node in the graph
and then did a connectivity check between that node and the source or
target. For large graphs this could result in major bottleneck because
this is needlessly traversing the graph multiple times. This commit
reworks the internals of these functions to use Dijkstra's algorithm to
find paths from or to the specified node. This actually matches how
networkx implements these functions and should significantly improve
the runtime performance of the functions. 
The only tradeoff with this is that results come back unordered now
instead of node creation ordered as with the prior implementation.
=> Use Dijkstra's algorithm for ancestors/descendants

.travis.yml
Since the release of cibuildwheel we no longer need to install it from
source to get support for non-x86 architectures. At the same time the
sdist job was missing the install of setuptools-rust and building the
sdist was failing. This commit updates all the release artifact jobs to
use a consistent version of cibuildwheel and fix the sdist job.
=> Update release artifact jobs

Cargo.toml, README.rst, setup.py
The retworkx repository has been moved into the Qiskit/ github
organization. As part of this migration we need to update some of the
package metadata and documentation to take into account the new URLs for
the repository. This commit updates those post-migration.
=> Update package metadata after migration to Qiskit/

.gitignore, .travis.yml, CONTRIBUTING.md, setup.py, tests/test_ancestors_descendants.py, tests/test_edges.py, tests/test_floyd_warshall.py, tests/test_layers.py, tests/test_nodes.py, tests/test_pred_succ.py, tox.ini
To ease local development this commit adds a tox config to run tests
and style/lint checks locally. It also updates the unittests to pass
flake8 which will be used for style rule checking on the tests.
=> Add tox.ini and lint for tests

README.md
Adds a comment to the README on how to enable nightly rust on MacOS.
=> Document enabling nightly rust on MacOS.

.travis.yml
The travis x86 linux wheel job is not working because when it calls sudo
pip the job tries to use a python 2 version of pip which no longer works
(nor does it have a cibuildwheel package on pypi that is compatible with
it). This commit removes the sudo usage to ensure we're always using
python3 pip.
=> Remove sudo from pip calls in travis wheel jobs

.travis.yml, azure-pipelines.yml
For the 0.3.3 release we switched to using a newer cibuildwheel in azure
pipelines for building macos wheels. This resulted in an invalid wheel
be uploaded for most users. This commit fixes this issue by switching
back to the previous travis job which is known working and use that
instead.
=> Rely on travis for macos wheel builds

.travis.yml
After the recent travis planned outage for a database upgrade the s390x
jobs are stuck in the queueing state and never run. This is blocking
development. This commit temporarily disables the s390x job until the
issue is resolved.
=> Temporarily disable s390x travis job

.cargo/config
When developing on macOS attempting to just build the shared lib without
installing via setuptools-rust would lead to a linker error. This lead
those developing on macOS to often use cargo build to get debug syntax
and compiler errors in a good format and then switch to using pip for
testing that library actually could link and compile. However, this
issue is actually documented in the PyO3 README and it explains that
macOS needs additional linker flags to work. This commit adds the
necessary flags which should enable cargo build to fully compile on
macOS.
=> Fix issue with cargo build on macOS

Cargo.toml, docs/source/api.rst, src/lib.rs, tests/test_edges.py
This commit upgrades the version of PyO3 being used to the latest
release 0.9.0 which had some api changes that needed to be taken into
account. Additionally, the new version has improved docs which show how
to add arguments to the __new__() constructor definition with a default
value. So while the new construct is being updated to use the new class
initializer an optional argument is added.
=> Upgrade PyO3 and option to enable check_cycle at init

.travis.yml
This reverts commit 28b97e7e8607f7df6792252fbce26d9a45737558.
Now that the issue with the s390x jobs in travis has been resolved
re-enable the job.
=> Revert "Temporarily disable s390x travis job (#55)"

.travis.yml
The travis coverage job has stopped working, it looks like because of
several new releases of grcov. This reverts to the version which was
working for previous commits.
=> Fix travis coverage job

Cargo.toml
This commit bumps the pyo3 version again to be the latest release. It's
only a bugfix patch release, and it shouldn't effect the usage in
retworkx, but better to keep up to date when we can.
=> Bump pyo3 version

.travis.yml
The rustfmt and compile test is failing right now because the pinned
nightly toolchain we're installing to get a working nightly rustfmt no
longer works. This commit fixes this by adjusting the job config to just
use the nightly toolchain and pin only rustfmt to a known working
version.
=> Fix rustfmt job to use newer toolchain

.travis.yml
The coverage job requires setting the -Zno-landing-pads flag, however on
the current version of rust nightly this flag has been removed (see:
rust-lang/rust#70175) and the job is no longer working. This commit works
around this by removing the flag to fix the job (see mozilla/grcov#427
for more details).
=> Remove invalid flag for coverage job

docs/source/api.rst, src/graph.rs, src/lib.rs, tests/graph/test_adj.py, tests/graph/test_edges.py, tests/graph/test_nodes.py
This commit adds a new class to retworkx PyGraph which is used to build
an undirected graph. Right now it only supports basic operations for
adding/removing nodes and edges and some graph queries (like neighbors,
etc). Additional, algorithms will be added for this in the future.
TODO:
Fixes #34
=> Add PyGraph class for undirected graphs

src/graph.rs, tests/graph/test_deepcopy.py
The PyGraph class was missing a __getstate__ and __setstate__ function
which were needed to enable support for pickling and deepcopy. This
commit adds the missing methods so PyGraph objects can be deepcopied.
One note on the test is that there aren't isomorphism functions that
support the pygraph type yet due to typing constraints a new trait will
need to be added for both PyGraph and PyDAG to leverage the existing
function. Until then the tests just assert that deepcopy() doesn't raise
and returns a PyGraph object.
=> Add support for deepcopy/pickle to PyGraph

.travis.yml
The s390x travis environment has a lot of issues, this is why we haven't
built wheels for s390x. Additionally, it looks like the configuration of
/tmp in the s390x is not working, users have reported issues with space
limitations [1] and in #75 the job is failing because pip can't use /tmp to
build a numpy wheel. Until all of these are fixed and the ci environment
for s390x is more stable this commit makes the CI job non-blocking.
[1] https://travis-ci.community/t/no-space-left-on-device-for-system-z/5954/10
=> Allow failures on the s390x travis job

Cargo.toml, docs/source/api.rst, setup.py, src/graph.rs, src/lib.rs, tests/test_adjacency_matrix.py
This commit adds 2 new functions to the retworkx module,
graph_adjacency_matrix and dag_adjacency_matrix for returing the
adjacency matrix as a numpy array for PyGraph and PyDAG respectively.
=> Add adjacency_matrix functions

Cargo.toml, setup.py
While the next release is probably a little while away enough new
features have landed since 0.3.4 that we can safely know that the next
release is 0.4.0. In preparation for that this bumps the version strings
in the setup.py and Cargo.toml, this is mostly to facilitate testing so
that we know when we're comparing a released version vs current master.
=> Bump version strings

docs/source/api.rst, src/graph.rs, src/lib.rs, tests/test_adjacency_matrix.py
This commit fixes an edge case with the adjacency matrix functions
around holes in the node indexes. Previously the nodes were assumed to
be contiguous but in the case of node removals it was possible to have
holes in the list of indexes. This would result in a matrix that was
larger than expected because it was building it based on the maximum
number of nodes during the lifetime of the graph. To fix this issue a
new attribute is added to PyDAG and PyGraph to track if nodes have been
removed. If nodes have been removed a mapping of node_ids to compressed
indexes are built and as the edges are iterated over the compressed
index is used in the matrix. If no nodes are removed the mapping step
is skipped since it is unecessary.
=> Fix edge case with *_adjacency_matrix() functions

docs/source/api.rst, src/graph.rs, src/lib.rs, tests/graph/test_edges.py, tests/graph/test_nodes.py, tests/test_edges.py, tests/test_nodes.py
This commit adds 2 methods to PyDAG and PyGraph, add_nodes_from() and
add_edges_from(). These methods take in lists of objects to add to the
graph to minimize the back and forth calling when adding many objects to
the graph at once. add_nodes_from() takes in a list of objects which
will be the data for the node, and add_nodes_from() takes in a list of
tuples with 2 node indexes for where the edge should be added and the
3rd tuple element is the data for the edge.
=> Add add_nodes_from and add_edges_from methods

docs/source/api.rst, src/astar.rs, src/lib.rs, tests/test_astar.py
This commit adds a new function for finding the shortest path from a
node to a node that satisfies an arbitrary condition. This is built
using the astar algorithm from the [upstream petgraph lib](https://github.com/petgraph/petgraph), however
because the data for the graphs being traversed are `PyObject`s we needed
to be able to handle python exceptions gracefully (instead of panicking)
which was not possible with the [upstream astar function](https://github.com/petgraph/petgraph/blob/master/src/astar.rs). So this
function has been forked into retworkx and modified to handle `PyResult<>`
wrapped returns from the callables and ensure the inner exception would be passed back to python.
TODO:
=> Add astar shortest_path function for PyGraph and PyDAG

docs/source/api.rst, src/graph.rs, src/lib.rs, tests/test_all_simple_paths.py
This commit adds 2 new functions dag_all_simple_paths() and
graph_all_simple_paths() to find all simple paths between 2 nodes in a
PyDAG and PyGraph object.
=> Add all_simple_paths for dag and graph

docs/source/api.rst, retworkx/__init__.py, src/dag_isomorphism.rs, src/digraph.rs, src/lib.rs, tests/test_adjacency_matrix.py, tests/test_all_simple_paths.py, tests/test_astar.py
This commit makes 2 changes, the first is that the rust class PyDAG is
renamed to be PyDiGraph. This makes it more clear that the class can be
used for any directed graph, not just a DAG. The PyDAG class is then
added as a subclass without any changes on the python side of the
module. This will enable a seamless transition for current users where
the only class exposed is PyDAG. Additionally, it will let users
differentiate between a PyDAG and PyDiGraph. Idealling we would want to
only have the cycle checking options exposed for the PyDAG class, but
there isn't any harm if PyDiGraph has it too.
Corresponding with this change the class code for PyDiGraph was moved
to a separate module to make it easier to follow. After this commit
lib.rs only contains the algorithms function code and the …
=> Rename PyDAG to PyDiGraph and reorganize modules

docs/source/api.rst, src/lib.rs, tests/graph/test_edges.py, tests/test_all_simple_paths.py, tests/test_astar.py, tests/test_edges.py, tests/test_nodes.py
There were several custom extension classes being defined in retworkx
that were never being exported to the retworkx module. This left users
in a weird position where a custom exception would be raised from a
retworkx call but they would be unable to import that exception class
from retworkx to catch it. This commit fixes this issue by adding the
exceptions to the module so that python code can use the exceptions. The
tests and docs are updated accordingly to use the newly exported
exception classes instead of the base Exception class (which is the
parent for all of retworkx's exceptions).
=> Actually export exception types

.travis.yml, README.md, tools/install_rust.sh, tools/install_rust_no_rustup.sh
This commit adds an s390x wheel job to CI that will run at release time
so we publish wheels for s390x too. We haven't been publishing or
building wheels for pypi since an issue with the manylinux2014 s390x
images and installing rust via rustup combined with disk size limits in
the s390x travis environment preventing use of the offline installer.
The travis issues have now been resolved so we now have enough space
to use the offline rust installer. For the next release we'll be
building s390x wheels.
=> Add s390x wheels

.travis.yml
This commit updates the flags used for generating coverage data with
grcov based on the latest README for grcov. [1] The last time these were
updated in #72 was to remove a flag that was being removed from rust and
causing the job to fail. However, that commit failed to add equivalent
flags which would perform the same functionality. This commit fixes that
oversight so we should have more reliable coverage collection.
[1] https://github.com/mozilla/grcov/blob/master/README.md
=> Update coverage rustflags

Cargo.toml, docs/source/api.rst, src/digraph.rs, src/lib.rs, tests/test_random.py
This commit adds 2 new functions directed_gnp_random_graph and
undirected_gnp_random_graph. These 2 functions are used for generating
a random Erdős-Rényi/binomial graph. The implementation of these 2
functions is based on the networkx function fast_gnp_random_graph. [1]
[1] https://github.com/networkx/networkx/blob/networkx-2.4/networkx/generators/random_graphs.py#L49
=> Add *_gnp_random_graph functions

.conda-rtd-environment.yml, .readthedocs.yaml, docs/source/conf.py, docs/source/requirements.txt
Since #90 the docs are now autogenerated from the installed retworkx
package. However, the readthedocs builds are not working because they
do not have rustc installed in their build env so it is unable to build
retworkx. This commit attempts to configure readthedocs to install rust
via conda and then use that to build retworkx.
=> Attempt to fix readthedocs build

src/digraph.rs, src/graph.rs, src/lib.rs
This commit reworks the functions and methods that were using a `Python` input
parameter as part of their operation. Requiring Python as a parameter means
that function has a GIL lock for it's entire operation which can have unnecessary
overhead,. In addition everywhere that we use a `Python` object means we're
calling out to python which will have overhead even if there is no GIL contention
so we should try to minimize except where necessary.
For example, generation of the output list from the `out_edges()` and
`in_edges()` methods for `PyDiGraph`/`PyDAG`. Previously these
methods were manually looping over the edges and constructing a Vec of
PyObjects from a tuple. This ends up being a performance bottleneck
because we need to call out to python on each iteration to convert the
tuple to …
=> Avoid use of Python in methods and functions

docs/source/requirements.txt, src/digraph.rs, src/graph.rs, src/lib.rs
This commit fixes some small oversight in the docs. Primarily it adds
them. This is important mostly so that python's signature inspection is
aware of the arguments to the function. Sphinx doesn't always reliably
detect the signature from it. The other thing is a couple of missing
docstrings are added.
=> Small docs cleanups

Cargo.toml
There has a been a new minor version of hashbrown up for some time now.
This commit bumps the dependency version in the cargo.toml to keep the
dependency version up to date.
=> Bump hashbrown version

.conda-rtd-environment.yml, .readthedocs.yaml, docs/source/conf.py, docs/source/requirements.txt
Since the introduction of the `to_dot()` methods in #103 and the use of
jupyter-sphinx in the docs, the read the docs builds have been failing.
It looks like this is due to:
https://github.com/jupyter/jupyter-sphinx/issues/126
This commit fixes this issue by pinning the jupyter sphinx version to
a version that is known working on read the docs.
=> Downgrade jupyter-sphinx to fix readthedocs build

Cargo.lock, azure-pipelines.yml
We document that the minimum rust version we can compile with is 1.39.0.
However, we only ever test with the latest stable release (and nightly in
the case of the coverage job) so it's not clear when/if we introduce a
dependency on a newer version of the rust compiler to build retworkx.
This commit adds a new minimum supported rust version job that builds
retworkx with the MSRV 1.39.0 and runs tests on it that way we can catch
when something changes.
=> Add job testing the minimum supported rust version

Cargo.lock, src/digraph.rs, src/graph.rs, tests/graph/test_nodes.py, tests/test_nodes.py
This commit adds implementations for the `__getitem__`, `__setitem__`, and
`__delitem__` mapping protocol methods to the PyGraph and PyDiGraph
classes. This enables accessing nodes from the graph by using standard
dict/mapping access patterns (ie `graph[2]`) with the node index. This
makes it easier to work with methods and functions that return node
indexes without having to call helper methods.
=> Implement mapping protocol methods for graph classes

docs/source/api.rst, docs/source/index.rst, retworkx/__init__.py, src/generators.rs, src/lib.rs, tests/generators/test_cycle.py, tests/generators/test_path.py, tests/generators/test_star.py
This commit adds a new module to retworkx, generators, which contains a
bunch of helper functions to quickly create various types of graphs. To
start it adds generators for a star graph, path graph, and cycle graph.
We can continue to grow this set out over time.
=> Add generators module

.travis.yml
Recently the coverage reporting job has started missing files and lines
and reporting things inconsistently. This commit attempts to correct
this by updating the grcov call based on the latest grcov documentation.
=> Try to fix coverage reporting job

src/dot_utils.rs, tests/test_dot.py
This commit adds quotes around label attributes in the output from the
to_dot() methods. Previously the string was just passed raw to the
output, but this would cause issues in graphviz when trying to parse the
dot file if there were spaces or other restricted characters in the
string (eg having a label like '1 -> 2'. To fix this this commit puts a
quotes around a label string if its present to handle this case.
=> Quote label strings in to_dot() output

README.md
This commit adds a section to the README about building retworkx from
source in develop mode. This can be useful while developing to enable
using an interactive debugger because it builds without optimizations
and including the debuginfo (for example its how we build retworkx to
collect coverage info in CI), However, because pip install -e doesn't
work having a description of how to build and install in develop mode
is useful to include in the README.
=> Add section to README about building in develop mode

setup.py
The license was not set for the python package metadata directly. We
listed the trove classifier for the project being apache licensed but
without specifying the license field certain parsers don't know what the
library is licensed under. This commit fixes the oversight and sets the
license field to apache 2.0.
=> Add license to python package metadata

Cargo.lock
To avoid potential bugs and version mismatches between libs this commit
updates the cargo lock file to update everything to the latest version. In local
testing this has a mild performance improvement too.
=> Update second level deps in cargo lock

Cargo.lock, Cargo.toml, src/digraph.rs, src/lib.rs
This commit switches the HashSet usage in retworkx to use hashbrown's
version of HashSet instead of the version in std::collections. This
provides a performance boost primarily from the use of the AHash default
hash algorithm. It also opens up potential future performance
improvements with hashbrown's rayon support to use parallel iterators.
At the same time since we're already listing rayon as a dependency
in #112 this adds the rayon feature to hashbrown in the cargo.toml
to expose the ParallelIterator traits for hashbrown's HashMap and
HashSet types. While this isn't being used yet it's potentially
useful in the future for #86.
=> Use HashSet from hashbrown instead of std::collections

src/lib.rs, tests/test_layers.py
This commit handles an error case in the retworkx.layers() algorithm
function when an invalid node index is part of the list passed in for
the 'first_layer' arg. Previously, this would result in a PanicException
being raised by PyO3 and include a backtrace from rust, this is because
the layers function was unconditionally pulling the node index from the
inner graph without checking whether it was a valid index or not. This
commit fixes this behavior and checks the data in the graph for that
index. If there is no data we raise an appropriate exception with an
exception message including the bad node index.
=> Handle invalid index in first_layer arg for layers() func

Cargo.lock
In preparation for the 0.5.0 release this commit updates the cargo lock
file with the latest versions of all the dependencies. This will make
sure the versions for reproducible builds are up to date and have the
latest bug fixes.
=> Update cargo lock file to prepare for release

Cargo.toml, src/lib.rs
Prior to this commit retworkx wasn't specifying an edition and was
implicitly using rust 2015. There wasn't any particular reason for this,
mainly just an ommision when the project was first created. This commit
updates the project to use the newer edition 2018 so we can get some
nice syntax features if needed.
=> Use rust edition 2018

Cargo.lock, src/lib.rs
This commit moves away from using a column-major fortran layout for the
ndarrays generated in library functions that return a numpy array. A
common use case for these arrays is to pass it from numpy (which is
how they're returned) to another C extension. While numpy can natively
handle all sorts of memory layouts for arrays, not everything accessing
the array in memory can. To make this easier and to avoid copying
in end user programs this removes the `.f()` used to tell ndarray to use
a fortran layout when allocating the array. There wasn't ever really a
reason for this besides sloppy copy and paste when we started using
ndarray with rust-numpy.
=> Use contiguous C arrays instead of fortran layout

src/lib.rs, tests/test_floyd_warshall.py
This commit adds a new option to the digraph_floyd_warshall function to
treat the input directed graph as undirected. When set each edge in the
directed graph will be treated as bidirection/undirected for the
generated output distance matrix.
=> Add option to digraph_floyd_warshall to treat input as undirected

retworkx/__init__.py, src/digraph.rs, src/graph.rs
This commit improves the documentation for the graph class. THe previous
class documentation didn't really include any details on the usage of
the classes or how they work. Instead it was just pointing people to
petgraph saying retworkx's classes are built around petgraph assuming
that was enough for users to figure out how to use the class. This
commit reworks the documentation to better explain how the classes are
used and provide examples on how to use it.
=> Improve graph class docs

Cargo.lock, src/digraph.rs, src/graph.rs, tests/graph/test_deepcopy.py, tests/test_deepcopy.py
In `__setstate__` for PyDiGraph and PyGraph there was an implicit
assumption that there was always a node in the graph. However if an
empty graph object was being unpickled it would cause a panic because
at one point we tried to find the maximum node index which returns None
if there is no maximum and we unconditionally unwrapped it instead of
handling a None. This commit fixes this issue by returning early if the
list of node indices is empty.
Fixes #164
=> Fix unpickling on empty graphs

src/lib.rs, tests/test_random.py
When p=0, we'll have an empty graph with n nodes and zero edges.
When p=1, we'll have a complete graph with n n(n-1) edges
for directed graphs and n(n-1)/2 edges for undirected graphs.
The time complexity stays the same. Let m be the max number of edges,
then run time is O(n+p*m), which reduces to O(n) when p=0 and, when
p=1 becomes O(n+n(n-1)) = O(n^2).
Fixes  #172
=> Change G(n,p) to accept exact 0 or 1 probabilities 

src/lib.rs
In #174 the gnp random functions were extended to support values of 0
and 1 for the probability representing either empty of full graphs. In
that change comparisons between the value of probability and 1 were used
to check if it's a full graph and we should just fast path adding an
edge between every node. However, when running `cargo clippy` on this it
rightfully points out that we should probably check for equality to 1
within an error margin (given that floating point is never exact).
Clippy suggested replacing using `std::f64::EPSILON` as the error value,
which is ~2.2e-16 [1] and replacing the comparison with:
```rust
(probability - 1.0).abs() < error
```
This commit just makes that change. While this is unlikely to cause any
issues in practice, because probability is a parameter and …
=> Fix cargo clippy errors

Cargo.lock, Cargo.toml, src/digraph.rs, src/graph.rs, src/lib.rs
Since PyO3 0.12.0 the trait implementations for converting from
hashbrown's HashMap and HashSet types. [1] This commit leverage
this so we do not have to internally convert these objects to and from
python types.
[1] https://github.com/PyO3/pyo3/pull/1114
=> Rely on PyO3 type conversion for HashMap and HashSet

docs/source/api.rst, src/lib.rs, tests/test_random.py
This adds two G(n,m) graph generators, one directed and one undirected.
The generated graph will be a random graph out of all the possible
graphs that are n nodes and m edges with max n*(n-1) edges for directed
graphs and n*(n-1)/2 for undirected graphs, avoiding self-loops and
multigraphs. The run time is O(n+m)
Fixes #174
=> Add G(n,m) random graph generator

src/digraph.rs, src/graph.rs, tests/graph/test_edges.py
This commit adds a new method remove_edges_from() to remove multiple edges in a single call.
Fixes #177
=> Add remove_edges_from method to PyGraph

tests/graph/test_edges.py, tests/test_edges.py
This commit adds some additional unit test coverage for
remove_edges_from which was recently added in #179. There are a couple
of coverage holes for the method, while manually testing works as
expected making sure we have coverage to avoid future regressions is
useful.
=> Expand test coverage for remove_edges_from

src/lib.rs
This commit updates the gnp random graph functions to internally use
Uniform.sample() instead of rng.gen_range(). The rand docs for
gen_range() recommend the use of Uniform if you're going to getting
random values in a range more than once, as the gen_range() function is
optimized for the single sample case. [1][2]
[1] https://docs.rs/rand/0.7.3/rand/trait.Rng.html#method.gen_range
[2] https://docs.rs/rand/0.7.3/rand/distributions/uniform/struct.Uniform.html
=> Switch gen_range() to Uniform in random graph functions

.github/workflows/main.yml, .github/workflows/wheels.yml, .travis.yml, setup.py
Python 3.9.0 was released on 10-05-2020, this commits marks the support
of Python 3.9 in qiskit-ignis. It adds the supported python version in
the package metadata and updates the CI configuration to run test jobs
on Python 3.9 and build wheels for Python 3.9.
=> Add support for Python 3.9

.github/workflows/wheels.yml
In #168 we added support for 3.9 which included the CI config to publish
Python 3.9 wheels. However as was caught in #186 it neglected to remove
the Python 3.9 skip for the win32 wheel job. This commit corrects the
oversight so when we push a release we build a Python 3.9 wheel for
win32.
=> Unskip Python 3.9 win32 wheel job

docs/source/requirements.txt
The recent sphinx 3.3.0 release today has started causing doc build
failures in CI. This is being caused by an issue with the m2r2 extension
used to render the README in the docs builds (see CrossNox/m2r2#13).
This commit caps the sphinx version until there is a new m2r2 release
fixing compatibility with sphinx >=3.3.0.
=> Cap Sphinx to avoid docs build failure

pyproject.toml, setup.py, tox.ini
The recent setuptools-rust 0.11.4 release dropped support for python
3.5, but didn't expose a minimum python version when doing so. This
means that on python3.5 pip will install the latest incompatible version
and fail to build retworkx (see PyO3/setuptools-rust#85). To workaround
this issue this commit sets a version cap for setuptools-rust when using
python 3.5. After the upcoming 0.6.0 release we will drop support for
python 3.5 so this can be removed then.
=> Cap setuptools-rust version for python 3.5

src/generators.rs, tests/generators/test_cycle.py, tests/generators/test_path.py, tests/generators/test_star.py
Fixes #184 .
> Allows users to pass optional parameter 'bidirectional' to add edges in both directions
> For directed_star_graph generator if 'bidirectional' is set to 'True', the 'inward' parameter is ignored.
=> Added Bidirectional parameters for directed graph generators

src/digraph.rs, tests/test_edges.py
This commit adds 2 new methods to the PyDiGraph class,
insert_node_between() and insert_node_between_multiple. These methods
are for inserting edges between a node and another node that has edges.
You specify a node and which node to insert it between and it will loop
over either the incoming or outgoing edges and add edges between the
existing edges.
=> Add insert_node_on_in_edges and insert_node_on_out_edges methods

docs/source/api.rst, src/iterators.rs, src/lib.rs, tests/test_pred_succ.py
This commit changes the return type of the bfs_successors function to be
a custom class BFSSuccessors. This new return class implements both the
sequence protocol and iterator protocol. This means that aside from
explicit type checking it should be backwards compatible with the list
being previously returned. It can be used with either index based access
or iterated over.
This should be more efficient for large graphs because instead of doing
the copy and type conversion and iterating over the entire nested Vec of
results it instead does it per access (either via `__getitem__` or
`__next__`). It does add a small amount of overhead for smaller graphs but
it is minimal since the function returns in microseconds in such cases
so a 10-20% overhead is not a big dea).
It's worth noting while …
=> Add custom iterator class for BFS successors return

tests/test_nodes.py
In #131 the `merge_nodes()` method was added as part of the larger feature
being added. In that PR though there wasn't any testing of the error
conditions or when the node weights were different. This commit covers
those edge cases to fix the coverage gap and enforce the current
behavior moving forward.
=> Expand unit test coverage for PyDiGraph.merge_nodes()

.travis.yml, tools/install_rust_no_rustup.sh
During the 0.6.0 release the travis jobs for building the release wheels
on aarch64, ppc64le, and s390x all failed because of some requirements
conflicts between the travis python environment and the requirements for
twine. The wheels were built successfully but the upload to PyPi failed
because of this requirements issue. This commit fixes that so future
releases should be able to upload the wheels. At the same time the rust
version used for the s390x jobs are updated is updated to the latest
stable release to keep the compiled binaries using the same version of
rustc.
=> Fix non-x86 release jobs

src/iterators.rs, tests/test_custom_return_types.py, tests/test_pred_succ.py
This commit implements the rich comparison method of the python object
protocol for the BFSSuccessors class. This enables doing an equals and
not equals comparison between a BFSSuccessors object and any other
python sequence. If will compare all the elements of the 2 and return
appropriate result. Previously this was not implemented so you would
have to cast a BFSSuccessors object as a list first to compare it which
would iterate over the object. Implementing the method avoids the need
to do this.
=> Implement rich comparison for BFSSuccessors

docs/source/api.rst, src/digraph.rs, src/graph.rs, src/iterators.rs, src/lib.rs, tests/test_custom_return_types.py
This commit adds a new return type NodeIndices that is used as the
return type for functions that return Vec<usize> when its used as the
return type to return a list of node indices. This custom type implements
the Python sequence protocol and can be used as the list which was
previously returned except for where explicit type checking was used.
Just as in #185 the advantage here is that for large lists of node
indices the type conversion from a Vec<usize> to list(int) becomes a
large bottleneck. This avoids that conversion and only does a usize to
python int conversion on access.
Related to #71
=> Add NodeIndices return type

src/astar.rs
In the astar.rs module it keeps a couple of HashMaps to track the path
and scores as the algorithm is going through the graph. Those HashMaps
were using the std collections HashMap type. However, in the rest of
retworkx the hashbrown HashMap is used. This is because the hashbrown
version is faster by default (because it uses a non-DOS resistant hash
function which is faster) and also supports parallelism. This commit
updates the astar.rs module to be consistent with the rest of retworkx
and use hashbrown, which will improve performance of the function.
=> Switch HashMap implementation in astar to use hashbrown

Cargo.lock, Cargo.toml, MANIFEST.in
This commit fixes a couple of packaging bugs with the current release of
retworkx. The first issues is that ndarray just released 1.14.0 which
raised the minimum supported rust version to 1.42.0 which is
incompatible with retworkx's minimum of 1.39.0. This caps the ndarray
package to only a compatible version with 0.13. The second issue was the
Cargo.lock was not included in the sdist. This means that when pepople
go to build from sdist via pypi (or anywhere else) the reproducible
build versions of all the dependencies are not used. This can cause
issues like the ndarray incompatibility which is blocking source builds
right now. The last thing is the cargo lock file is updated to pull in
the latest version of pyo3, 0.12.4 which fixes a potential security
issue with the earlier 0.12.x …
=> Update package, cap ndarray, and include cargo lock in sdist

src/digraph.rs, src/graph.rs, src/lib.rs
This commit fixes some issues with the documentation and text_signature
attribute for methods. The documentation of digraph_union needed a bit
of cleanup and more details to explain how it works. The other issue
fixed here is the text_signature attribute for methods were missing the
'self' parameter. While the self is implicit in the typical call,
without it in the text_signature attribute the sphinx builds assume the
first parameter in the signature is self, and removes it from the
documentation. This commit fixes this by adding self to all the method
signature attributes.
=> Fix documentation and signature issues

docs/source/api.rst, src/digraph.rs, src/graph.rs, src/iterators.rs, src/lib.rs, src/union.rs, tests/test_custom_return_types.py
This commit adds 2 new return types `EdgeList` and `WeightedEdgeList`
that are used as the return type for functions that return
`Vec<(usize, usize)>` and `Vec<(usize, usize, PyObject)>` respectively.
This custom type implements the Python sequence protocol and can be
used as the list which was previously returned except for where
explicit type checking was used. Just as in #185 and #198 the
advantage here is that for large edge lists the conversion from
Rust to a Python type becomes a large bottleneck. This avoids that
conversion and only does it per element on access.
=> Add EdgeList and WeightedEdgeList return types

docs/source/api.rst, src/lib.rs, tests/test_collect_runs.py
This commit adds a new algorithms function, collect_runs(), which is
used to find a list of runs in a PyDiGraph object that match a specified
condition. A run in this context is any linear path inside the graph.
The condition is specified using a python function that will be passed a
node's data payload/weight object and will return whether it matches the
condition or not. The intended use case for this function is with
qiskit-terra's PyDiGraph method collect_runs() which is implementing
this algorithm currently in Python on top of PyDiGraph (it will also be
used by a future method collect_1q_runs which is being added in
Qiskit/Qiskit-terra#5431).
TODO
=> Add collect_runs() function

.conda-rtd-environment.yml
In #214 we updated the documentation configuration to use the new
qiskit sphinx theme to be consistent with qiskit's documentation and
also add the use of reno for release notes. However, that PR did not
update the conda environment file used by read the docs for buidling the
documetation to include the new requiremetns. This commit corrects that
oversight and adds the missing dependencies to the docs builds.
=> Fix the read the docs builds

releasenotes/notes/fix-segfault-is_dag_fn-8335e900ffca6af9.yaml, src/lib.rs, tests/test_edges.py
Previously the retworkx.is_directed_acyclic_graph() function was
internally using the petgraph::algo::is_cyclic_directed function to look
for a potential cycle in the graph. However, as noted in the docs[1]
this function is recursive and as reported in Qiskit/qiskit-terra#5502
with very large graphs this is causing segfaults. To avoid this
potential issue this commit changes the internal implementation to use
petgraph::algo::toposort which isn't recursive and should be more
reliable.
Fixes: Qiskit/qiskit-terra#5502
[1] https://docs.rs/petgraph/0.5.1/petgraph/algo/fn.is_cyclic_directed.html
=> Switch is_directed_acyclic_graph to use toposort internally

src/lib.rs
Rust 1.49.0 was recently released which included a new version of
clippy with new checks. When running cargo clippy with 1.49.0 a new
warning was introduced. This commit makes the style change so that
clippy doesn't highlight any issues.
=> Make clippy changes from rust 1.49.0

src/digraph.rs, src/graph.rs, src/k_shortest_path.rs, src/lib.rs, src/union.rs
This commit replaces uses of ::new() for container types (like Vec and
HashMap) with with_capacity(). The difference between the 2 is that
with_capacity() makes the initial memory allocation with N elements of
the given type in the container (and still grows when it's exceeded)
while new() just makes a minimal initial memory allocation and relies on
more allocations. So it becomes a tradeoff between using potentially
excess memory vs th overhead of additional memory allocations. So for
cases where we have an idea of the final size of the container object it
makes sense to avoid the memory allocation and just do a large one up
front.
=> Avoid allocation overhead with_capacity() instead of new()

Cargo.toml
This commit changes the release build configuration to use full LTO for
retworkx release builds. The tradeoff this makes is compile time vs
optimization. It basically serializes the compilation of retworkx's
dependencies so that it can do link time optimization. From benchmarking
the performance gains are modest (in the best case ~2-5%), but it
still seems worth it since most users don't constantly rebuild retworkx
and just use the prebuilt binaries that are included in the wheels on
PyPI so tuning the release builds at the cost of compile time seems
worth it.
=> Use full LTO for release builds

.conda-rtd-environment.yml
The read the docs builds are using conda to install rust and other
system dependencies required to install retworkx and build the docs.
However, the version of rust was pinned at 1.40 which is now too old
after #224 merged which bumped the minimum supported rust version from
1.39.0 to 1.45.0 because of a newer version of pyo3. This commit updates
the read the docs conda env to use the latest stable rust release 1.49.0
so that we can build retworkx for docs builds again.
=> Fix read the docs builds by updating rust compiler version

.github/workflows/main.yml, Cargo.lock, Cargo.toml, README.md, releasenotes/notes/bump-msrv-d581a8cbeff8915b.yaml
This commit reverts the version bumps for pyo3, numpy, and ndarray. The
3 changes here required increasing the minimum supported rust version
from 1.39.0 to 1.45.0. While for most developers and use cases this is
fine since 1.45.0 is > 6 months old and most packagers/distributors keep
the rust version up-to-date. One known exception to this though is the
debian 10 rustc package is at 1.41.0. This becomes an issue for
raspberry pi users running a 32bit operating system (the aarch64
manylinux wheels on PyPI work fine for 64bit OS rasberry pi users).
The piwheels project is using the debian 10 package which means to
provide prebuilt wheels of retworkx they need to be able to use rustc
1.41.0 to build.
When weighing the features of this version bump (the big thing for our
use case are better …
=> Revert "Bump pyo3 from 0.12.4 to 0.13.1 (#224)"

src/digraph.rs, src/lib.rs
This commit fixes some small rust lint issues caught with the nightly
version of clippy (rust 1.51.nightly) which has some additional rules
enabled. The vec![] usage should have a minor performance improvement
over the Vec::new() and push() that was used before but it is likely not
noticeable in practice.
=> Fix rust lint issues

releasenotes/notes/add-from_adjacency_matrix-3a1122b86aeb4dd8.yaml, src/digraph.rs, src/graph.rs, tests/test_adjacency_matrix.py
This commit adds a new constructor method from_adjacency_matrix() to
PyGraph and PyDiGraph classes. This enables creating a new graph from an
input adjacency matrix.
=> Add constructor to build graphs from adjacency matrices

releasenotes/notes/update-edge-407745423983c801.yaml, src/digraph.rs, src/graph.rs, tests/graph/test_edges.py, tests/test_edges.py
This commit adds 2 new methods to the graph classes, update_edge and
update_edge_by_index, which are used to update the data payload/weight
of an edge in the graph in place. Prior to this the only way to update
an edge would be to remove it and add a new edge with the new data
payload which may change the edge index (assuming something was using
it).
=> Add APIs to update an edge's data payload inplace

docs/source/api.rst, releasenotes/notes/add-universal-functions-1e54351f1f7afa4b.yaml, retworkx/__init__.py, tests/test_dispatch.py
In the rust generated Python API we need to have fixed class inpurts to
satisfy the traits used by the pyo3 macro generated FFI functions. This
results in duplicate methods like digraph_dfs_edges and graph_dfs_edges
with the same implementation just differing input types. To simplify the
API for users this commit adds universal functions to the python side of
the retworkx package to take in any retworkx graph object and dispatch to
the proper function in the rust generated api that relies on strict
input types.
Fixes #215
=> Add universal methods

.github/workflows/wheels.yml, releasenotes/notes/arm64-mac-d45deda145e37b8f.yaml
With the recent release of cibuildwheel 1.9.0 support for building arm64
binaries on macOS was added. This enables us to build release binaries
for this new platform. However, these binaries will be cross-compiled
and not tested since there are no CI resources with the platform
available. This commit adds a new release wheel job to build a aarch64
binary and publish an arm64 wheel for macOS. This will enable users who
have an arm64 mac to run retworkx without having to either build from
source or run under rosetta 2.
Fixes #231
=> Add release job to publish macOS arm64 binaries

CONTRIBUTING.md
Removes trailing spaces and fix a typo in the document.
=> Fix a a typo in the CONTRIBUTING document

releasenotes/notes/neighbors-fn-returns-unique-indices-00109eda7e3c9ee7.yaml, src/digraph.rs, src/graph.rs, tests/graph/test_neighbors.py, tests/test_neighbors.py
Fixes #249 
petgraph's underlaying `neighbors()` method returns duplicated
nodes in multigraphs (on a per-edge basis). The desired behavior
for the public API is not to include these repetitions though.
This commit collects the returned indices in a HashSet to remove
duplications, then it exhausts the set with `drain()` and
collect it into a list.
This commit also adds new tests to check there is no duplication
in the list of neighbors indices and adapt the existing tests to
ignore the order.
=> Ensure uniqueness of neighbor indices returned by `neighbors()`

.travis.yml
Since the Rust 1.50.0 the s390x CI test job has been failing. This looks
to be caused by rust-lang/rust#80810. Until the issue is resolved in a
released version of rust this pins the rust version used in the job to
the previous release 1.49.0 which does not have this issue and should
work fine.
=> Pin rust in s390x test job

.travis.yml
This commit switches the architecture tag for the arm64 travis jobs to
use arm64-graviton2 instead. The arm64-graviton jobs are hosted on
Amazon's graviton2 CPU ec2 nodes which should be faster (not that the
regular arm64 nodes were slow).
=> Try using arm64 graviton2 instead of arm64

releasenotes/notes/add-multigraph-pygraph-fc77ffd1b7812da3.yaml, src/dag_isomorphism.rs, src/digraph.rs, src/generators.rs, src/graph.rs, src/lib.rs, src/union.rs, tests/graph/test_edges.py, tests/test_edges.py
This commit adds a new kwarg, multigraph, to the PyGraph and PyDiGraph
constructors. When this is set to `False` the created graph object will not be a
multigraph and only one edge will exist between nodes. If a parallel
edge is attempted to be added it will be ignored since the edge already
exists.
=> Add option to set multigraph on PyGraph and PyDiGraph

.github/workflows/main.yml, .travis.yml, Cargo.lock, docs/source/api.rst, releasenotes/notes/add-max-weight-matching-089ba67668b3b071.yaml, src/lib.rs, src/max_weight_matching.rs, tests/test_max_weight_matching.py, tox.ini
This commit adds a new python function max_weight_matching() for
computing the maximum-weighted matching of a PyGraph object. The
implementation of this function is based on “Efficient Algorithms for
Finding Maximum Matching in Graphs”, Zvi Galil, ACM Computing Surveys,
1986. [1] It is basically a porting of the networkx implementation of
the algorithm [2] with some additional inspiration from the prototype for
the networkx version (it's basically the same code but some aspects were
a bit clearer to figure out from the prototype rather than networkx's
copy of it). [3][4]
Fixes #216
[1] https://dl.acm.org/doi/10.1145/6462.6502
[2] https://github.com/networkx/networkx/blob/3351206a3ce5b3a39bb2fc451e93ef545b96c95b/networkx/algorithms/matching.py
[3] http://jorisvr.nl/article/maximum-matching …
=> Add max weight matching function

src/dot_utils.rs, src/lib.rs, src/max_weight_matching.rs
In rust 1.50.0 the new version of cargo clippy is highlighting a warning
on an unecessary result on the output for a closure, since the closure
is always returning true (so there is no possibility of an error output.
However, this is ignoring that the closure is passed to a function and
the return type expected by that function has a Result<> return. If we
were to remove the result from the closure that would become a type
mismatch. To avoid clippy raising an issue in this instance this commit
adds allow on that lint rule for that line.
=> Fix issues found with newer cargo clippy versions

.travis.yml
The arm64-graviton2 nodes are not being correctly allocated and are
showing as an x86_64 architecture (it looks like they're not even
running on amazon ec2). Since this defeats the purpose of the arm64
ci jobs (to test on arm64) this commit reverts the change to graviton2
and uses the regular slower arm64 nodes, which are actually run on arm
cpus.
This reverts commit bbcb0d55c1dbb0c575b1be3a29a9594e3bb68a14.
=> Revert "Try using arm64 graviton2 instead of arm64 (#253)"

docs/source/api.rst, docs/source/index.rst, docs/source/networkx.rst
This commit adds a new documentation guide for current networkx users on
how to start using retworkx or how to migrate existing networkx code. It
provides a high level explanation of the differences in behavior between
the 2 libraries and how you can you can switch between them.
Fixes #248
TODO:
=> Add guide on using retworkx for networkx users

docs/source/api.rst, releasenotes/notes/add-is_matching-334626fe47e576be.yaml, src/lib.rs, tests/test_matching.py, tests/test_max_weight_matching.py
This commit adds new functions for checking a provided matching set is
valid, is_matching(), and that a provided matching set is valid and
maximal, is_maximal_set(). This pairs with #229 and can be used to
partially check the output from the max_weight_matching function added
there. Equivalent functions were implemented in #229 using Python for
the tests in #229 and those tests should be updated to use these
functions instead.
Fixes #255
=> Add is_maximal_matching and is_matching functions

releasenotes/notes/add-gc-integration-87f0d20a92b3e614.yaml, src/digraph.rs, src/graph.rs
Right now the 2 graph classes in retworkx, PyGraph and PyDiGraph, did
not integrate with the Python garbage collector. This would result in
memory not being cleared in a running python process even if retworkx
objects were only created in temporary context. This commit attempts to
fix this by implementing the garbage collection protocol [1] which
should enable python to clean up retworkx objects when they're no longer
being used.
[1] https://pyo3.rs/v0.12.4/class/protocols.html?highlight=garbage#garbage-collector-integration
=> Add GC support to graph objects

Cargo.lock, releasenotes/notes/return-class-object-methods-d8b19d952639118a.yaml, src/iterators.rs, tests/test_custom_return_types.py
This commit adds a few more methods from the Python object protocol to the
custom return types. All the classes now have a `__str__` method so you can
see the contents of the custom returns with a `print()`. Additionally, a
`__hash__` is added to each class since the return types are immutable.
However, for return types that contain `PyObject`s (`WeightedEdgeList` and
`BFSSuccessors`) if any of the objects contained are not hashable this
will raise an exception (just as if you called `hash()` on that object).
The last methods are related to garbage collection in python which
enables the Python garbage collector to cleanup the custom return types.
=> Add more object protocol methods to custom return types

.github/workflows/wheels.yml, .travis.yml
For the recent 0.8.0 release all the wheel jobs failed because we added
networkx as a test requirement (for comparing the outputs of
max_weight_matching()) but were not installing networkx before running
unit tests. This made all the wheels come back as broken because
unittests failed. This commit fixes that issue by adding networkx as an
explicit test requirement in all the cibuildwheel job configurations.
Additionally, the ppc64le wheel jobs started failed for an additional
reason, it appears that the travis CI images aren't up to date and need
the rust compiler to install cryptography (which is required for pip and
other packages). This commit fixes those jobs so we can install
cibuildwheel and also build the packages.
=> Fix CI wheel jobs

.github/workflows/main.yml, .github/workflows/wheels.yml, .gitignore, .travis.yml, CONTRIBUTING.md, tests/.stestr.conf, tests/test_max_weight_matching.py, tox.ini
Since #229 our test runs take significantly longer. This is mostly a
function of the tests added in that function running over numerous
random graphs and comparing the output against networkx to verify it
works in all cases. However, this validation comes with a runtime cost.
In an attempt to mitigate this partially this commit changes the test
runner from stdlib's unittest runner to use stestr. [1][2][3] stestr
provides a performance improvement by running tests on parallel workers
and also provides an easier to use UI that enables test selection a
history of previous runs, and many other features. The test suite in
retworkx will still need to be strictly unittest compatible so anyone
can run with stestr, stdlib unittest, pytest, or any other test runner
of their choice. But the default …
=> Use stestr for test jobs

.cargo/config
Building the retworkx library on macOS requires some extra rustc linker
flags so that cargo and rustc are able to link the binary against python
correctly at build time. To do this by default we added the cargo config
for the x86_64 macOS target in #53 which fixed it for all users running
cargo on those platforms. However, now there are macOS systems that have
aarch64 CPUs. To ensure that people trying to use cargo to build
binaries on those systems don't need to manually specify the linker
flags this commit adds the config for that target as well.
=> Fix cargo builds on arm64 macOS systems

docs/source/api.rst, releasenotes/notes/expand-isomorphism-cfb646cfef66fa25.yaml, retworkx/__init__.py, src/dag_isomorphism.rs, src/isomorphism.rs, src/lib.rs, tests/test_dispatch.py, tests/test_isomorphic.py
Resolves #268.
Introduced changes:
- Vf2 implementation in `dag_isomorphism.rs` now works with `StableGraph` so we can pass the graph that `PyGraph` and `PyDiGraph` store.
- Optional `edge_matcher` argument to compare edge data.
- Unified api in a single `is_isomorphic` call.
- Retain `retworkx.is_isomorphic_node_matching` for backwards compatibility.
=> Make vf2 generic

.travis.yml
The ppc64le CI job has started to fail recently when installing rustup
to bootstrap a rust environmnet in the CI node. The error states that
there is already a system rust installation and that it will conflict
with rustup's version of rust. Since apparently rust is preinstalled on
the travis ppc64le CI nodes now this commit attempts to fix the error
by skipping the rustup step and using the preinstalled rust compiler.
=> Skip rustup installation for ppc64le CI job

.github/workflows/main.yml, README.md
The retworkx default branch has been renamed from 'master' to 'main'. To
ensure we're actually running CI and links work this commit updates some
dangling references left in the repository to the previous default
branch name.
=> Update CI for renamed default branch

docs/source/api.rst, releasenotes/notes/add-random-layout-c1c2751be971e5d0.yaml, retworkx/__init__.py, src/iterators.rs, src/lib.rs, tests/digraph/test_layout.py, tests/graph/test_layout.py, tests/test_custom_return_types.py
This commit adds a new function `random_layout()` which is used to
generate a random layout for a graph that can be used in visualization.
This is necessary for building a matplotlib drawer (issue #298 and a
first draft of the implementation #304). To make the function more
efficient it also adds a new custom return type `Pos2DMapping` which is
used to build an immutable readonly dict compatible result container for
the output type from this function.
Related to #280
=> Add random_layout function and Pos2DMapping

releasenotes/notes/fixed-mutability-0ab3030db0d77239.yaml, src/digraph.rs
This commit fixes a small overight in the predecessor_indices() and
successor_indices() methods for PyDiGraph. These functions were
previously set so they get a mutable borrow of self, but did not mutate
the contents of the graph object. This caused potential issues if/when
these methods were used in a context where there was another reference
to the graph object (like if they were used in the callback nethod for
a graph method) that would raise an error when the method was called.
This commit corrects this oversight by correctly setting the reference
to self to be immutable.
=> Fix mutability of self on successor/predecessor indices methods

src/generators.rs
The logic around adding edges in directed_path_graph() was a bit more
complex then necessary. Regardless of whether bidirectional is set or
not we're always adding an edge, bidirectional only should control
adding the reverse edge. This commit simplifies the logic to remove the
unecessary else.
=> Simplify bidirectional logic in directed_path_graph()

.travis.yml
In recent weeks we've seen a spike in job timeouts and other spurious
failures for the ppc64le CI. It looks like the travis ppc64le
environment is facing some issues. Since none of the recent failures
have caught any real code issues when running or building on ppc64le
and are all caused by infrastructure issues, this commit adds it to
the allowed failure list. We can remove it when and if the ppc64le ci
environment stabilizes.
=> Allow failures on ppc64le linux travis jobs

Cargo.lock
Since we're planning to release later this month, this commit bumps the
dependency versions in the Cargo.lock to the latest versions for
everything where we're not constrained by the MSRV, mainly ndarray and
num-complex (which cargo tries to update as deps of numpy). This will
likely be needed again right before the release, but at least in the
meantime we can get some more testing in with the latest versions of
the dependencies before that.
=> Bump dependencies in Cargo.lock file

docs/source/_templates/versions.html
This commit adds a missing template file for the qiskit-sphinx-theme.
PR #329 previously attempted to fix the RTD docs builds and update the
theme formatting. While that worked fine for PR mode after it merged the
builds for the latest version of the docs did not work and fail with an
error about the missing template file. This will hopefully fix the
builds so we can see the rendered docs for the current state of the main
branch.
=> Add missing doc theme template file

docs/source/_templates/versions.html, docs/source/conf.py, tools/deploy_documentation.sh, tools/other-builds.txt
This commit adds support for keeping multiple released versions of the
documentation on the documentation page. It will keep a single version
of the doc for each minor release of retworkx (for example 0.8, 0.9,
etc). Each tag documentation build will upload it's built docs to both
the latest stable url and the appropriate url on stable/. The version
table for the drop down will also be populated with the previous versions
from 0.8 to current.
TODO:
=> Add stable versions to the documentation

releasenotes/notes/add-num-methods-08ac0963b9961f5e.yaml, src/digraph.rs, src/graph.rs, tests/digraph/test_edges.py, tests/digraph/test_nodes.py, tests/graph/test_edges.py, tests/graph/test_nodes.py
This commit adds two new methods num_nodes() and num_edges() to the
graph classes for returning the number of nodes and edges respectively
in the graph. While a user could do len(graph) to get the number of
nodes having an explicit method also is useful as it might not be
obvious that you can use len() on the graph.
=> Add methods to get number of nodes and edges in the graph

releasenotes/notes/add-copy-method-f2abb1222b323dab.yaml, src/digraph.rs, src/graph.rs, tests/digraph/test_copy.py, tests/graph/test_copy.py
This commit adds a new copy() method to the graph classes to return a
shallow copy (with shared references to weight/data payload objects) of
a graph object.
=> Add copy() method to graph classes

docs/source/conf.py, docs/source/requirements.txt
Now that we've moved our docs publishing away from read the docs to our
own hosting we are no longer constrained by the build environment for
read the docs as we're running builds in github actions now. This means
we no longer need to pin our sphinx version, or jupyter-sphinx version
for our docs jobs. This commit updates the docs requirements list and
the sphinx config to no longer pin these requirements.
=> Remove sphinx pinning

docs/source/networkx.rst
This commit adds documentation to the retworkx for networkx users guide
on the differences between networkx and retworkx when it comes to matrix
generation. Right now retworkx only has an `adjacency_matrix()` function
which is equivalent to networkx's `to_numpy_array()` and returns a numpy
array of the adjacency matrix. This is different from networkx's
`adjacency_matrix()` function which returns a scipy sparse array (and is
just an alias for networkx's `to_scipy_sparse_matrix()`). Documenting
this gap is important because it's easy to get confused by these API
differences.
This difference is fundamentally because we can effeciently create numpy
arrays in retworkx by just pass a pointer to numpy with a 2d array
that was constructed natively in rust (using rust-numpy) while other
matrix …
=> Add section to retworkx for networkx users guide on matrix converters

.github/workflows/wheels.yml, .travis.yml
This commit bumps the cibuildwheel version we use for the release jobs
to the latest release.
=> Bump cibuildwheel version to latest release

.gitignore, docs/source/api.rst, docs/source/networkx.rst, docs/source/visualization.rst, releasenotes/notes/pydot-drawer-c5df0aa830679748.yaml, retworkx/visualization/__init__.py, retworkx/visualization/graphviz.py, setup.py, tests/visualization/test_graphviz.py
This commit adds a section to the retworkx for networkx users guide on
visualizations. This is important especially for the ``mpl_draw``
function since it's mostly identical to the ``networkx_drawer`` function
but there are some key differences to keep in mind.
This commit also makes small change to the graphviz drawer, the name of
the function is renamed from `pydot_draw` to `graphviz_draw` and the
Python module is renamed from `pydot` to `graphviz`. This was done to
be more descriptive as graphviz is the backend not pydot. It also makes
it easier to migrate away from pydot in the future if we needed to since
the key piece is using graphviz not a particular python interface to it.
Fixes #341
=> Add visualization to retworkx for networkx users guide

docs/source/api.rst, docs/source/networkx.rst, releasenotes/notes/0.8.0/add-universal-functions-1e54351f1f7afa4b.yaml, releasenotes/notes/0.8.0/prepare-0.8-f3ec8cbf07dfdbb7.yaml
Step towards #328. This PR changes the documentation by:
* Organizing algorithms by theme instead of splitting them into universal and type specific
* Creating two new sections for type specific algorithms in the docs, called Retworkx Advanced API
* Functions that have no `graph_*` or `digraph_*` equivalents are listed under Algorithms section instead of the type Advanced API section; no function is listed twice
This PR is opinionated, and is open to debate. Because the themes can be arbitrary, there could be other groupings. 
The proposed documentation groups every algorithm that did not belong to a theme under `Miscellaneous`. It also only groups algorithms under the Advanced Retworkx API if they are called by a dispatcher, otherwise they are listed under Algorithms.
=> Major rework in documentation

.github/workflows/main.yml, Cargo.toml, docs/source/conf.py, setup.py
Now that 0.9.0 is out the door this commit bumps the package version on
the main development branch to enable landing new features. It doesn't
look like we're going to have a bugfix release (and if we do we can just
branch from the 0.9.0 tag). Bumping the version strings enables us t
differentiate the development branch from the previous release.
=> Bump version post-release

tox.ini
This commit fixes the tox job configuration so we actually install the
requirements for running the graphviz drawer tests. To run the graphviz
drawer tests you need graphviz installed in addition to the retworkx
extras requirements 'graphviz' (which contains pillow and pydot).
However, prior to #339 the extra was called 'pydot' not 'graphviz' and
this was never updated in the tox.ini. This has resulted in the graphivz
drawer tests all being skipped because we're not installing the python
requirements in the test environment. This commit fixes this oversight
and configures tox to install the correct extra so we can run the tests
(at least on linux where we install graphviz in CI).
=> Fix execution of graphivz tests in CI

.gitattributes, tools/setup.ps1
This commit adds a new gitattributes file to mark the documentation
and release note directories as containing documentation (and therefore
excluding them from language statistics on github). This is documented
here: https://github.com/github/linguist/blob/master/docs/overrides.md
=> Add a gitattributes file for linguist

src/iterators.rs, tests/test_custom_return_types.py
An approach for #350.
Right now in our custom return types we have some duplicate boilerplate code and the appropriate logic is inside `__richcmp__`, `__str__` and `__hash__`  functions. This PR moves the logic into separate traits and implements them for native rust types and PyObject. This allows us to introduce convenient macro rules to expand the definition of our custom iterator based on the input types and name. Hopefully this approach makes it easy and fast to introduce new return types (?).
That being said, I am a little bit concerned about the performance. For example, we need to acquire the python Gil even for methods that we don't actually use it (is there any chance that compiler will optimize this?). In any case, even if we decide that this approach makes sense, we should …
=> Refactor custom return types

releasenotes/notes/multigraph-option-in-to-undirected-b56af4f26816be61.yaml, src/digraph.rs, src/lib.rs, tests/digraph/test_to_undirected.py
Closes #369.
Instead of relying to the default graph api that would keep the *last* edge data among the parallel edges we see, i added an optional weight_combo_fn` argument that combines all edge data. Do note here that if `weight_combo_fn` is omitted, the behavior is the same as the default graph api.
=> Add multigraph option to`PyDiGraph.to_undirected`

releasenotes/notes/non-induced-subgraph-isomorphism-710f5a21565abf06.yaml, retworkx/__init__.py, src/isomorphism.rs, src/lib.rs, tests/digraph/test_subgraph_isomorphic.py, tests/graph/test_subgraph_isomorphic.py, tests/test_random.py
This commit adds a kwarg `induced` in `is_subgraph_isomorphic` to determine if we should check for a *node-induced* subgraph or *not* induced. Previously, only node-induced case was supported.
In not induced case, the changes are minimal: we shouldn't  check `R_new` pruning rule and check neighbors in `R_suc` and `R_pred` rules only in the second graph.
=> Add induced kwarg in `is_subgraph_isomorphic`

src/digraph.rs, src/dot_utils.rs, src/lib.rs, src/max_weight_matching.rs
In the current nightly version of rust's clippy a new check for finding
unnecessary borrows on variables was added. This check has identified
several places we're passing a borrowed references that wasn't
necessary. This commit just fixes those places identified by nightly
clippy so that when rust 1.55 is released we don't have any issues.
=> Remove unnecessary borrows from code

src/isomorphism.rs
This PR removes the unstable sort and the (unnecessary) use of a `HashSet` that would make the result of VF2++ heuristic matching order non-deterministic.
=> Stabilize Vf2++ matching order

tests/digraph/test_edgelist.py, tests/graph/test_edgelist.py
In the test_invalid_return_type_weight_fn edge list test methods we're
occasionally seeing CI failures caused by an error in cleanup. The test
method calls a write_edge_list() method of the graph objects that will
raise an exception, however to prevent leaking a temp file an addCleanup
call was added protectively. However, whether the file gets written or
not is not deterministic on every platform (apparently especially on
macOS). To avoid a spurious CI failure this commit adds a custom
function to handle any exceptions raised during cleanup and treat them
as non-fatal.
=> Handle non-existent files in edgelist cleanup

Cargo.lock, Cargo.toml, src/lib.rs
Petgraph 0.6.0 was just released, this commit bumps the version in the
cargo.toml to the new release. It also updates some of the petgraph
usage to take advantage of some new features.
=> Bump petgraph version to the latest release

tests/digraph/test_edgelist.py, tests/graph/test_edgelist.py
In #380 we updated the tests to fix some tests when in macOS CI the
,write_edge_list() negative tests were not actually writing a file to
disk which was causing a failure in the cleanup phase. However, that PR
missed a test case which had the same bug and the issue isn't actually
fixed. This commit corrects that oversight and handles a non-existent
file in cleanup for the test cases which were missed.
=> Really fix macOS CI failures

releasenotes/notes/dijkstra-path-bugfix-2c3f8f16d40c47b9.yaml, src/dijkstra.rs, tests/digraph/test_dijkstra.py, tests/graph/test_dijkstra.py, tests/graph/test_num_shortest_path.py
This commit fixes an issue with the dijkstra path functions where they
were returning the incorrect result in the case of multiple paths
between nodes in the graph. Previously, in cases of parallel paths the
inner rust dijkstra function was not updating the path if it had a
shorter weight than the already found path. This could result in an
incorrect shortest path being returned, depsite the shortest length
being correct. This fixes this by making sure we always update the path
when we set the distance. Additionally, after fixing this several of the
dijkstra path tests began to fail because they were not returning the
correct result.
Fixes #387
=> Fix incorrect result with dijkstra path functions

Cargo.lock, Cargo.toml, docs/source/api.rst, releasenotes/notes/add-dag_weighted_longest_path_length-5c4e9a7d19c97d4d.yaml, src/lib.rs, tests/digraph/test_depth.py
As a follow up to #383 what the underlying Qiskit user case for #381
would like is to use floats for the edge weighting. However for the
existing `dag_longest_path_length()` function our hands are tied with the
return type being an unsigned integer for backwards compatibility. To
workaround that limitation this commit adds a new function
`dag_weighted_longest_path_length()` which requires a weight function and
works with `f64` weights. To accomplish this, the inner `longest_path()` rust
function is made generic for any numeric type returned by the callback
function, which required leveraging the num-traits crate. The new
pyfunction is then just a thin wrapper that works with `f64` instead of
`usize`.
=> Add weighted longest path functions

src/lib.rs
This commit removes an unnecessary `.collect()` on the node indices from
being used in `_floyd_warshall()`. To build the output container the
function was looping over the node indices. Previously it was building a
`Vec` by iterating over the contents of `graph.node_indices()` and then
proceeding to iterate over the vec. Instead we can remove the
intermediate `Vec` and directly iterate over the `NodeIndices` iterator
returned by `graph.node_indices()`.
This was caught by clippy on rust nightly which will save us from having
to fix this at a future date when a new rust version is released.
=> Remove unnecessary .collect() from _floyd_warshall()

.github/workflows/main.yml
This commit leverages a new beta feature in github actions, concurrency
groups [1], to enable job auto cancellation when there is a PR update.
Basically we define a unique concurrency group for each PR and limit
the group to only run a single workflow at once and cancel any existing
jobs when a new one is launched. This should hopefully improve CI
throughput by not running duplicate jobs on PR updates and only running
CI on the latest commit of a PR branch if there are multiple workflows
queued.
[1] https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
=> Leverage concurrency groups to auto cancel jobs

src/shortest_path/floyd_warshall.rs, src/shortest_path/mod.rs
Updates graph_floydwarshall_numpy and digraph_floydwarshall_numpy
to share a single inner function that works for both graph types and returns a 2D array. 
This deduplicates the code, similarly to #405
=> Deduplicate floyd_warshall_numpy implementation

releasenotes/notes/adjacency_matrix_fixes-6e8c937398346c44.yaml, src/digraph.rs, src/graph.rs, tests/digraph/test_adjacency_matrix.py, tests/graph/test_adjencency_matrix.py
This commit fixes an issue with the handling of null values in the
from_adjacency_matrix for PyDiGraph and PyGraph. Previously, the
function incorrectly treated any value <= 0 as a null value and didn't
add an edge for that. But the behavior should have been != instead of
less than or equal to. Additionally, the null value of 0.0 was hard
coded into the constructor methods which precluded using different
values. This commit fixes both issues by adding a new kwarg, null_value,
that lets users specify the null value they'd like to use. Additionally,
the behavior is changed to just use a not equals comparison to enable
using negative values (assuming null_value is zero).
Fixes #408
=> Fix handling of null value in from_adjacency_matrix

releasenotes/notes/fix-node-holes-bug-in-number-weakly-connected-components-addafef7d39f5471.yaml, src/connectivity/mod.rs, tests/digraph/test_weakly_connected.py
`number_weakly_connected_components`  returns wrong answer if the graph has holes in the node indices. This commit modifies the source code of `petgraph::algo::connected_components` to handle this case.
=> Fix `number_weakly_connected_components` if holes in node indices.

Cargo.toml, docs/source/conf.py, setup.py
Now that the 0.10.x release is out the door we should bump the version
string on main to show the source version we're installing is newer
than what's been released. This bumps the version strings to 0.11.0. If
we decide to do another bugfix release in the 0.10.x series we can
create a banch from 0.10.1 and go from there.
=> Bump version strings post release

.github/workflows/main.yml
The coverage ci job uses the rust nightly channel to enable the coverage
collection. However, building with nightly has recently stopped working
because of a change breaking num-bigint (see
https://github.com/rust-num/num-bigint/issues/218 for more details).
Until the rustc nightly behavior is reverted or a new num-bigint version
is released that is compatible with the new nightly behavior this commit
pins the nightly version used in the coverage job to a version prior to
the failure.
=> Pin nightly version in coverage job

releasenotes/notes/bugfix-vf2-parallel-edges-f8be125e255753f7.yaml, src/isomorphism/vf2.rs, tests/digraph/test_isomorphic.py, tests/digraph/test_subgraph_isomorphic.py, tests/graph/test_isomorphic.py, tests/graph/test_subgraph_isomorphic.py
Closes #429.
The solution is to build an adjacency matrix with entries equal
to the number of edges connecting a pair of nodes instead of
0/1 values.
=> Fix `is_subgraph_isomorphic` with parallel edges.

releasenotes/notes/bugfix-digraph-adj-b8a911fab80effec.yaml, src/digraph.rs, src/graph.rs, tests/digraph/test_adj.py
Documentation of `PyDiGraph.adj` states that the ouput dictionary
contains adjacent nodes in either direction. But previously, only
outbound neighbors were included. This has been fixed. At the same time,
this commit simplifies the source code of `PyDiGraph.adj_direction` and `PyGraph.adj`.
=> Return adjacent nodes in both directions in `PyDiGraph.adj`

docs/source/api.rst, releasenotes/notes/bugfix-union-7da79789134a3028.yaml, retworkx/__init__.py, src/digraph.rs, src/graph.rs, src/lib.rs, src/union.rs, tests/digraph/test_union.py, tests/graph/test_union.py
Previously, `digraph_union` would falsely keep or delete
edges if `merge_edges` is set to true. This commit fixes
the logic of `digraph_union` to skip an edge from the second
graph if both its endpoints were merged to nodes from the
first graph and these nodes already share an edge with equal
weight data. At the same time, a new function `graph_union`
was added that returns the union of two `PyGraph`s.
Closes #432.
=> Fixes `digraph_union` if `merge_edges` is set to true.

releasenotes/notes/bugfix-node-holes-210d1b4d329df6dc.yaml, src/lib.rs, src/shortest_path/distance_matrix.rs, src/shortest_path/floyd_warshall.rs, src/shortest_path/k_shortest_path.rs, tests/digraph/test_dist_matrix.py, tests/digraph/test_k_shortest_path.py, tests/graph/test_dist_matrix.py, tests/graph/test_k_shortest_path.py
Previously, `distance_matrix` and `k_shortest_path` would panic
if the input graph contained holes in node indices. This commit
fixes this in `distance_matrix` by mapping nodes to a compact interval
`0..n` where `n` is the number of nodes in the graph.
In `k_shortest_path` we should initialize a vector of `node_bound` size.
=> Fix `distance_matrix` and `k_shortest_path_lengths` if node holes.

.github/workflows/main.yml, .github/workflows/wheels.yml, setup.py, tox.ini
The release of Python 3.10 is coming soon on:[ 10/04/2021](https://www.python.org/dev/peps/pep-0619/#schedule). As of this
commit the second release candidate has been published which should be
stable to start testing. This commit adds the CI test jobs for all
platforms with Python 3.10 and updates the release wheel jobs to
including building python 3.10 wheels. In the interest of CI time this
commit also drops the win32 platform from the test matrix, as it
provides limited coverage over the win64 jobs and would be 5 (including
3.10) extra jobs.
Fixes #415
=> Add support and CI config for Python 3.10

Cargo.lock, Cargo.toml, src/digraph.rs, src/graph.rs, src/iterators.rs
Both PyO3 and rust-numpy released their 0.15.0 versions which added a
bunch of new feature (mainly on pyo3) and fixes. This commit upgrades
both to the latest release and fixes compatibility issues with the new
version.
Fixes #465
=> Upgrade to PyO3 and Numpy 0.15.0

docs/source/api.rst, releasenotes/notes/petersen-graph-7ebe5d3b4cc0c946.yaml, src/generators.rs, tests/generators/test_petersen.py, tests/graph/test_isomorphic.py
Related to #150 
Add a generator for generalized Petersen graphs [1]. That family of graphs has many interesting mathematical properties, and could be useful for both users and retworkx developers. This PR also adds test cases to our isomorphism code based on properties of those Petersen graphs.
[1]: https://mathworld.wolfram.com/GeneralizedPetersenGraph.html
=> Add generalized Petersen graphs generator

src/dag_algo/mod.rs
As was pointed out in #506 the docstring for the
`lexicographical_topological_sort()` function was not really clear as to
what it was or how it differed from the normal `topological_sort()`
function. This commit expands the docstring for the function to outline
specifically how it behaves.
Fixes #506
=> Improve docstring for lexicographical topological sort

releasenotes/notes/fix-degree-with-self-loops-5b40c45cc61fcebe.yaml, src/graph.rs, tests/graph/test_edges.py
Closes #517.
In an undirected graph, self-loops should increment by two (and not by one)
the degree of a node.
=> Fix `PyGraph.degree` if self-loops.

releasenotes/notes/fix-dispatch-3596ef110cc68338.yaml, retworkx/__init__.py
Closes #515.
This commit updates `dfs_edges` to set `source` argument to `None` by default and
fixes an oversight in `union` where user-defined values of `merge_nodes` and `merge_edges`
arguments were being ingored.
=> Fix dispatch function of `dfs_edges` and `union`.

releasenotes/notes/negative-weights-in-shortest-path-algos-b205b63bd12d1a26.yaml, src/lib.rs, src/shortest_path/all_pairs_dijkstra.rs, src/shortest_path/floyd_warshall.rs, src/shortest_path/mod.rs, src/steiner_tree.rs, tests/digraph/test_astar.py, tests/digraph/test_dijkstra.py, tests/digraph/test_k_shortest_path.py, tests/graph/test_astar.py, tests/graph/test_dijkstra.py, tests/graph/test_k_shortest_path.py
Some shortest path algorithms, like `dijkstra_shortest_paths`,
`dijkstra_shortest_path_lengths`, `all_pairs_dijkstra_path_lengths`,
`all_pairs_dijkstra_shortest_paths`, `astar_shortest_path`,
`k_shortest_path_lengths` give incorrect results if there are negative
edge weights. This commit adds a check that raises if a user-defined weight
function returns a negative or NaN value.
Closes #525.
=> Raise if negative weights in shortest path algos.

.github/workflows/main.yml, tox.ini
This commit updates the lint job definition in the tox.ini to work now
that we have workspaces in the rust package. In #459 we added a new
workspace for the dedicated rust package retworkx-core. But having
workspaces means that running cargo fmt outside from the tests/
directory (as we do with tox) means cargo doesn't know which workspace
to run against. To correct this issue this commit adds the --all flag to
the cargo fmt call in the tox job definition to ensure we're able to run
from any directory in the repo and check the formatting on all the rust
files in the project.
=> Fix cargo fmt call in tox.ini

README.md, pyproject.toml, setup.py, tox.ini
The setup.py has long carried around a pip install fallback if
setuptools-rust can't be imported. This was necessary as prior to the
introduction of pep-517 there was no way to express a build-system
requirement in python packaging. There is the setup_requires field in
the setuptools metadata, but this would both trigger the install too
late (as we need to import setuptools-rust prior to running
setuptools.setup()) and also fallback to using easy_install instead of
pip which complicates installation. With pep-517 we list setuptools-rust
as a build system requirement in the pyproject.toml and pip will just
install that prior to trying to run the setup.py in the sdist.
But, for users on older versions of pip, before pep-517 was supported,
this caused a cryptic error as there would just be …
=> Remove pip install setuptools-rust from setup.py

docs/source/api.rst, releasenotes/notes/connected-components-undirected-graphs-d81d3fb8c844ef83.yaml, src/connectivity/connected_components.rs, src/connectivity/mod.rs, src/lib.rs, tests/graph/test_connected_components.py
This PR introduces several functions: `connected_components`, `number_connected_components`,
`node_connected_component` and `is_connected` for finding connected component in an
undirected graph. Previously, only directed graphs were supported.
Closes #514.
=> Support undirected graphs in connected components.

README.md, releasenotes/notes/no-more-pydot-d57c3b0e7456e3d4.yaml, retworkx/visualization/graphviz.py, setup.py, tests/visualization/test_graphviz.py
Previously we were relying on the pydot library to call graphviz to
generate visualizations. This was done for simplicity since pydot is all
about providing a python API wrapper around graphviz. However, it does
this by parsing the dot files into it's own internal representation of
the graph description to provide a python api for interacting with it
prior to calling out to graphviz. For retworkx this is unnecessary as we
have a native function for generating dot files and we just need to pass
that directly to graphviz. Additionally, this parsing adds a place for
bugs to be introduced as was seen in #526 when a new version of
pyparsing (the dependency pydot uses to parse the dot files) started
causing invalid output to be generated. This commit updates the graphviz
drawer to stop using …
=> Remove optional dependency on pydot

src/digraph.rs, src/graph.rs, src/isomorphism/vf2.rs, src/steiner_tree.rs
Nightly rust, for 1.59, has added a couple of new clippy rules (or changed
existing rules) that will start causing an error in CI when rust 1.59 is
released. This commit fixes the issues identified by running nightly
clippy. These errors fall into 2 categories, replacing map().flatten()
with flat_map() and an unecessary late initialization.
=> Fix future clippy errors

retworkx-core/src/traversal/dfs_edges.rs, retworkx/__init__.py, src/traversal/mod.rs
Minor corrections in dfs_edge_neighbors pseudocode:
* mention `neighbors` instead of `edges`
* add missing `label v as discovered`
=> Minor corrections in dfs_edge_neighbors pseudocode

releasenotes/notes/edge-index-methods-427f7301c720f565.yaml, src/digraph.rs, src/graph.rs, tests/digraph/test_edges.py, tests/graph/test_edges.py
There were some gaps in working with edges in the graph class API.
Mainly when working with indices there was no method to acquire the
edge's data payload or endpoints easily. Additionally for the PyGraph
class didn't have a simple method to find incident edges directly
instead a user had to rely on neighbors() and get the edges from that
directly. This commit adds methods to fill these API gaps to make
working with edges a bit easier.
=> Add edge utility methods to PyGraph and PyDiGraph

releasenotes/notes/add-node-indices-3c7c37ed4ea75a2c.yaml, src/digraph.rs, src/graph.rs, tests/digraph/test_nodes.py, tests/graph/test_nodes.py
Since the earliest retworkx releases the method to return the list of
node indices in the graph was named "node_indexes". However as the
retworkx api evolved we standardized on the use of "indices" everywhere
else in the API. For backwards compatibility we kept the "node_indexes"
method name. This commit starts the process of migrating away from
"node_indexes" a new method "node_indices" is being added. The
"node_indexes" method is now just a backwards compatibility alias for
node_indices. In a future release when we start preparing for the
retworkx 1.0.0 release we will start emitting a deprecation warning
from node_indexes prior to its eventual removal in the 1.0.0 release.
=> Start migration from node_indexes -> node_indices

docs/source/api.rst, releasenotes/notes/online-topo-sort-f94bcd2064a5cde7.yaml, src/lib.rs, src/toposort.rs, tests/digraph/test_toposort.py
This PR implements a new class `TopologicalSorter` to topologically sort a directed graph.
It gives the ability to process nodes while they are becoming ready (i.e they have no unprocessed
predecessors) and then mark them as done, so more nodes can be freed.
`TopologicalSorter` wraps the underlying graph inside a `Py<..>` with GIL-independent lifetime
in order to avoid cloning the graph. The downside is that users may modify the graph while using
a `TopologicalSorter`, we do not guard against it and this might result in wrong outputs.
Closes #495.
=> Add online topological sorter.

src/connectivity/mod.rs
As was pointed out in #505 the cycle_basis() function doesn't work with
multigraphs, but this was missing in the documentation. This commit adds
a note to the docstring that it won't work correctly if a multigraph is
used with it.
=> Document cycle_basis() doesn't work with multigraphs

retworkx-core/src/connectivity/chain.rs, src/connectivity/mod.rs
This commit replaces the use of petgraph's recursive `depth_first_search`
in `chain_decomposition` with the iterative implementation we added in retworkx-core.
=> Use an iterative dfs-search in `chain_decomposition`.

docs/source/networkx.rst, retworkx/__init__.py, retworkx/visualization/matplotlib.py, src/connectivity/mod.rs, src/dag_algo/mod.rs, src/iterators.rs, src/layout/mod.rs, src/traversal/mod.rs, src/tree.rs
This PR removes most occurrences of "indexes" with "indices" in code, comments, and docs.
* Nothing in ./tests was changed. Perhaps all tests should be changed to use `node_indices` since this just wraps `node_indexes`.
* The two methods `node_indexes` that will likely be deprecated were, of course, not changed.
* release notes mentioning the addition of `node_indexes` were, of course, not changed.
=> Replace most occurrences of "indexes" with "indices"

docs/source/tutorial/introduction.rst
In #537 we added the tutorials to the retworkx documentation. The
introduction tutorial was heavily based (and used some phrases
verbatim from that document) from the similar tutorial in NetworkX.
While the final result is different as it's specific to retworkx the
basic outline and some of the high level details are the same so we
should provide credit to the original source. I noticed reviewing the
published documentation for the 0.11.0 that I neglected to provide
proper attribution of that as part of #537. This corrects that oversight
and adds a comment to the top of the documentation source to link to the
original networkx document which it was based off of.
=> Add attribution comment to introduction tutorial

.github/workflows/main.yml, .github/workflows/wheels.yml, Cargo.toml, README.md, docs/source/conf.py, releasenotes/notes/raise-msrv-and-mspv-7ad10b4e66f1383f.yaml, setup.py
Now that the 0.11.0 release is out the door this commit prepares the
main branch for development of the next minor version release, 0.12.0.
To do this it makes three changes, the first is to bump the package
version strings to the new version. This is primarily to differentiate
the development branch against the released 0.11.0. Second, this raises
the minimum supported rust version (MSRV) to 1.48. As was documented in
the release notes the 0.11.0 release was the last version to have an
MSRV of 1.41. Moving forward we'll support an MSRV of 1.48. This version
was chosen because it's what the latest version of Debian stable
currently packages, and we need to ensure that Debian can compile
retworkx for our userbase on raspberry pi (the raspberry pi python
package index, piwheels.org, uses …
=> Bump package version, raise MSRV to 1.48 and drop Python 3.6 support

.mergify.yml, CONTRIBUTING.md
This commit adds a mergify configuration to the repoistory. Mergify will
let us automate PR merging and backporting to stable branches. This
should hopefully simplify the maintainence of the repository as core
reviewers now we only need to tag a PR as "automerge" and the bot will
handle rebasing and merging for us. Additionally, it will automate the
backporting of PRs for us. This will enable us to maintain stable bugfix
releases more easily and hopefully avoid for tension like we had in
0.11.0 between getting a release out for Python 3.10 support and merging
the required features.
To facilitate the use of all these new tools this commit adds detailed
documentation to the contributing guide on code review, the use of
mergify, stable branches, and backporting.
=> Add mergify config and document how it's used

.github/workflows/main.yml
This commit fixes an oversight in our ci configuration. Starting after the
0.11.0 release we started maintaining a stable branch in parallel to our
main development branch. This branch is used to backport bugfixes from
main so that we can push out bugfix releases independently of our main
development branch. This reduces the pressure pressure to release as
frequently just to get bug or compatibility fixes out and we can develop
new features on our main branch and release when it's ready. However,
as part of this migration we neglected to updated the ci configuration
to run on the new stable branches. This commit fixes this oversight so
that we will run ci on backports in addition to our main development
branch.
=> Run CI on stable branches too

docs/source/tutorial/introduction.rst
In #537 we added the tutorials to the retworkx documentation. The
introduction tutorial was heavily based (and used some phrases
verbatim from that document) from the similar tutorial in NetworkX.
While the final result is different as it's specific to retworkx the
basic outline and some of the high level details are the same so we
should provide credit to the original source. I noticed reviewing the
published documentation for the 0.11.0 that I neglected to provide
proper attribution of that as part of #537. This corrects that oversight
and adds a comment to the top of the documentation source to link to the
original networkx document which it was based off of.
(cherry picked from commit eecaf914cb3db3f758735b70128d995b1d5cdedf)
=> [Stable] Add attribution comment to introduction tutorial (#554)

src/digraph.rs, src/graph.rs, src/iterators.rs
In PyO3 0.16.x the Python protocol interface was reworked to be more
pythonic and deprecated the pyproto macro and the distinct traits for
implementing different python protocols. As a side effect of that the
overlapping methods for the Python mapping and sequence protocols (they
both have getitem, len, etc). In the 0.16.3 release a pyclass macro
option was added to explicitly mark a container class as a mapping. In
retworkx we have several mapping containers which are not sequences. Now
that we're using PyO3 0.16.3 for retworkx, to make this distinction clear
this commit leverages the new mapping argument to the pyclass for
container classes which are just mappings.
=> Make mapping containers explicitly not sequences

releasenotes/notes/edgeindices-pygraph-523ed0feac553c18.yaml, src/connectivity/mod.rs, src/graph.rs, src/tree.rs, tests/graph/test_edges.py
This commit simplifies and deduplicates the PyGraph method definitions
that add edges to the graph object. When reviewing the multigraph=False
path to debug an issue I found that the PyGraph code around edge
handling was duplicated between every method that adds edges and also
was needlessly returning a PyResult<T>. This commit abstracts the edge
adding to an inner private method that does the multigraph flag handling
and also drops the PyResult return as these functions can't raise an
error. The return type for the functions which add multiple edges is
also updated to be an EdgeIndices object for a faster return time.
=> Simplify and deduplicate multigraph handling in PyGraph

.github/workflows/main.yml
In the recent Rust 1.60.0 release the instrument-coverage compiler flag
was stabilized. This means it no longer requires a nightly build of the
rust compiler to use it. This commit updates our coverage CI job to use
stable rust so we don't have to rely on a nightly build anymore.
=> Update coverage job to use stable rust

Cargo.lock, Cargo.toml, retworkx-core/Cargo.toml
This commit updates the retworkx-core crate dependency to have a fixed
version which matches the retworkx crates version. We're not going to be
in a situation where we we release retworkx-core separately from the
main retworkx crate we only want to support the main crate with the core
crate at the same version. This commit makes this relationship
explicitly. At the same time it fixes the version string in the
retworkx-core crate as it wasn't updated in #560 like it should have
been.
=> Update workspace configuration to be tied to specific versions

docs/source/tutorial/introduction.rst
This commit adds a section to the introduction tutorial on graph element
modification. It's a basic feature of interacting with a graph to show
how you can update a node or edge in place on an existing graph object
however this was previously not mentioned in the introduction tutorial.
This commit corrects this oversight by explaining how this can be done.
=> Add section to intro tutorial on graph element modification

releasenotes/notes/slices-for-sequences-a3b31c70f5d896b4.yaml, src/iterators.rs, tests/test_custom_return_types.py
This commit adds support for dealing with slice inputs to custom
sequence return types such as ``NodeIndices``. Previously, if a slice
was requested from a custom return type it would have raised a
``TypeError``. With this commit now it will return a new container object
with a copy of the data from the requested slice.
Fixes #590
=> Add support for slice inputs to custom sequence return types

docs/source/api.rst
In #544 we updated the autosummary directives output directory from
'stubs' to 'apiref' so that the urls of the hosted documentation made
more sense. Then a redirect was added to ensure that stale links to
stubs were redirected to the new location. However, as part of this
migration one autosummary directory was missed causing it to still
publish to 'stubs'. With the redirects in place this means that the
documentation is not actually reachable anymore. This commit fixes this
oversight by fixing the autosummary directory so the documentation is
built in the correct location.
Fixes #594
=> Fix stray reference to old autosummary dir

src/tensor_product.rs, tests/digraph/test_tensor_product.py, tests/graph/test_tensor_product.py
This PR fixes the implementation of tensor product for undirected graphs.
Example: 
``` Python
import networkx as nx
g = nx.path_graph(2)
h = nx.path_graph(2)
r = nx.tensor_product(g, h)
r.edges() # [((0, 0), (1, 1)), ((0, 1), (1, 0))]
```
However, this calculation in retworkx outputs `[((0, 0), (1, 1)), ((1, 1), (0, 0))]`.
I fixed the tensor product in retworkx to output the same result as networkx.
=> Fix implementation of tensor product for undirected graphs

src/graphml.rs, tests/test_graphml.py
GraphML documents may declare attributes/keys for `node`, `edge`, `graph` or `all` graph elements.
This commit adds support for attributes with domain `graph` and `all` by populating `Py(Di)Graph.attrs`
field with a dictionary since the first iteration of our GraphML reader would raise if users tried to
load a graphml file with keys declared for these domains.
Closes #607
=> Support graph attributes in GraphML reader.

docs/source/api.rst, releasenotes/notes/add-eigenvector-centrality-e8ca30e31738a666.yaml, retworkx-core/src/centrality.rs, retworkx/__init__.py, src/centrality.rs, src/lib.rs, tests/digraph/test_centrality.py, tests/graph/test_centrality.py
This commit adds a new function eigenvector_centrality() to compute the
eigenvector centrality of a graph. It uses the same power function
approach that the NetworkX function eigenvector_centrality() [1]
function uses. This is for two reasons, the first is that a more
traditional eigenvector linear algebra/BLAS function would either
require us to link against BLAS at build time (which is a big change
in the build system and a large requirement) or to call out to numpy
via python both of which seemed less than ideal. The second reason was
to make handling holes in node indices bit easier. Using this approach
also enabled us to put the implementation in retworkx-core so it can be
reused with any petgraph graph.
Part of #441
=> Add eigenvector centrality function

src/generators.rs, tests/generators/test_cycle.py, tests/generators/test_mesh.py, tests/generators/test_path.py, tests/generators/test_star.py
This commit makes some improvements to the internals cycle graph, path
graph, star graph, and  mesh graph generator functions to optimize the
performance and reduce the memory overhead when creating the graphs. The
improvements fall into a couple categories, first the graph memory
allocation is only done once now as opposed to on demand as we create
the graph, and second intermediate index lists are no longer used in
places they weren't required to avoid the overhead of having to maintain
dual `Vec`s.
Related to #623
=> Optimize performance of some generator functions

retworkx/__init__.py, src/digraph.rs, src/graph.rs
The graph classes use a unsigned 32 bit integer as the index type which
means the maximum allowed size for the number of nodes or edges in a
graph object is std::u32::MAX - 1, roughly 4 billion. We should document
this limitation. In theory we can change the index type to use a usize
(see #628 for where this was attempted) which would increase the upper
limit to 2**64 - 1 (on 64 bit platforms), but there is a significant
memory cost for this and to have graphs so large you will need a
significant amount of local memory. In the future we might add a new
large graph type that makes this tradeoff to enable scaling above 4
billion nodes or edges but for now this commit just documents the
limitation with the current graph types.
Fixes #623
=> Document maximum number of nodes in edges allowed in graph classes

paper.md
Closes #624 
Paragraph rewrite of the node indices section to make it clearer that indices are stable and stored in Rust
Also, took advantage to put #630 in the paper
=> Explain node indices

src/generators.rs
Closes #555.
Some other remarks:
- Fixed hyperlinks to paper in a couple of functions.
- The docs for `directed_heavy_square_graph` and `directed_heavy_hex_graph` did not use the respective functions in the example. I believe this was an oversight and have updated those code snippets. Hence, these functions' outputs will differ from the previous ones.
- Haven't updated the occurrences at:
https://github.com/Qiskit/retworkx/blob/657e291ee3e919f5219076ab2d453dc00a3f015b/src/graph.rs#L1129
https://github.com/Qiskit/retworkx/blob/657e291ee3e919f5219076ab2d453dc00a3f015b/src/digraph.rs#L1765
as these specify the usage of the `to_dot()` function specifically.
=> Removed usage of `pydot` in docs

.github/workflows/main.yml
In #644 we added the build/install of the rust coreutils package to the
retworkx backwards compat CI job  to have a consistent cross platform
way to set environment variables between different OSes. However, this
adds significant time to the CI job while we build this package. This
commit reconfigures the job to leverage github actions native
environment variable handling and drops the coreutils usage. This should
speed up the backwards compat jobs since we no longer are compiling
coreutils from source.
=> Remove coreutils build from retworkx backwards compat tests

docs/source/README.rst, docs/source/index.rst, docs/source/install.rst, docs/source/tutorial/introduction.rst, rustworkx/__init__.py, rustworkx/visualization/graphviz.py, rustworkx/visualization/matplotlib.py, src/digraph.rs, src/graph.rs, src/iterators.rs, src/toposort.rs, src/traversal/mod.rs
This commit improves some of the introductory material for the rustworkx
documentation. The introductory guides for rustworkx were a bit lacking,
partially because it inherited the basic install guide from the readme
and also because the introduction tutorial didn't cover the very
beginning of what rustworkx is or how to use it. This commit addresses
this by adding a dedicated install/getting started page which includes
a platform support table and adding a couple sections to the
introduction tutorial to cover basic installation and importing.
Additionally, the imports in the documentation are standardized on
aliasing rustworkx as rx.
This commit superscedes #559 which added the platform support table to
the readme.
=> Improve introductory documentation materials

src/digraph.rs, src/graph.rs, src/graphml.rs
In the recently released Rust 1.63 clippy added some new rules and also
improved detection on other rules. The new borrow_deref_ref rule is
being triggered by PyO3 macros and we need to wait for PyO3 0.17 to be
released to fix these errors.
=> Fix cargo clippy failures from Rust 1.63

tools/deploy_documentation.sh, tools/deploy_documentation_dev.sh
Fixes #664 
Pushes the documentation to both [https://qiskit.org/documentation/rustworkx](https://qiskit.org/documentation/rustworkx) and [https://qiskit.org/documentation/retworkx](https://qiskit.org/documentation/retworkx)
=> Push docs to both retworkx and rustworkx domains

docs/source/tutorial/betweenness_centrality.rst, rustworkx/visualization/matplotlib.py
Fixes #680 
Port of https://github.com/networkx/networkx/pull/5937
Avoids `TypeError: '_AxesStack' object is not callable` when calling `mpl_draw` in a graph object
=> Fix visualization failure with matplotlib 3.6.0

README.md
Closes #674, Related to #670
We link to the `dev` documentation until the release. We haven't released under the new name yet but I do understand people want a clickable documentation link
=> Temporarily link to dev rustworkx documentation

.github/workflows/main.yml, .github/workflows/wheels.yml, docs/source/install.rst, releasenotes/notes/manylinux2010-last-release-b649d25612cb80b8.yaml, setup.py, tools/install_rust.sh
For the upcoming 0.12.0 release it would be good to add support for python 3.11. While this hasn't been released yet it's currently a release candidate with a frozen C API. We're likely to release rustworkx 0.12.0 prior to the Python 3.11 release. In order to avoid having to have rustworkx be a blocker for any downstream packages looking to adopt 3.11 this commit proactively enables support for testing and building with Python 3.11 off the latest rc in order to ensure we're building binaries compatible with 3.11 for the 0.12.0 release.
=> Add support for Python 3.11

releasenotes/notes/add-index_output-dag-layers-d8329db4a1f76410.yaml, src/dag_algo/mod.rs, tests/rustworkx_tests/digraph/test_layers.py
This commit adds a new keyword argument, index_output, to the layers() function which is used to return a list of list of node indices representing the layers in the DAG instead of a list of list of node data payloads. The default output does not change, but for users that prefer to work with indices (which is probably a more natural return format for the function) this option allows them to work with indices.
Closes #646
=> Add index_output option to layers() function

constraints.txt
The recent release of importlib-metadata broke compatibility with stevedore on Python 3.7. Stevedore is a dependency of a dependency of stestr which we use for running tests in CI so this is blocking CI from working and tests from running locally with Python 3.7. This commit pins the importlib-metadata version in CI to unblock things.
=> Pin importlib-metadata in CI

.github/workflows/wheels.yml
This commit adds a CI job to automatically publish rustworkx-core to crates.io on releases. In the past I have just manually run cargo publish locally but this is error prone and depends on me doing the correct thing. Having it run automatically in CI limits the chances of something going wrong.
=> Add cargo publish job for rustworkx-core

.github/workflows/wheels.yml, .mergify.yml, Cargo.lock, Cargo.toml, docs/source/conf.py, rustworkx-core/Cargo.toml, setup.py
Now that the 0.12.0 release is out the door this commit bumps the version numbers to indicate that the main branch is now ahead of the 0.12.0 release. At the same time this commit fixes an indentation issue in the CI wheel publish jobs that we hit during the 0.12.0 release.
=> Bump version numbers after 0.12.0 release

Cargo.lock, Cargo.toml, src/digraph.rs, src/graph.rs, src/graphml.rs, src/iterators.rs, src/lib.rs, src/score.rs
Bumps PyO3 and NumPy to 0.17.2
It has been a while since dependabot has sent us updates notifications for PyO3 and we missed a couple. But I think bumping to 0.17.2 should work fine given the Rust MSRV is still the same and we have released 0.12
=> Update PyO3 to 0.17.2

.github/workflows/wheels.yml
There appears to be an issue with memory consumption under the hood when using QEMU with Rust cargo: 
https://github.com/rust-lang/cargo/issues/10583.
This is causing the CI wheel workflow to run out of memory and fail for QEMU-based jobs, e.g.:
https://github.com/Qiskit/rustworkx/actions/runs/3245206601/jobs/5420102493#step:7:325
From the discussion on the linked issue, the workaround is to tell cargo to use the Git executable directly, rather than `libgit2`.
=> Fix QEMU-based Linux wheel jobs.

.zenodo.json, CITATION.bib, README.md
Update citation to reflect https://doi.org/10.21105/joss.03968 🍾
=> Add New Paper Details

src/shortest_path/num_shortest_path.rs
Rust 1.65 was recently released which added some new clippy rules. This commit fixes the failure reported when running clippy with 1.65. This would have caused a CI failure as we start using the new rust version in CI.
=> Fix clippy error with new Rust 1.65 release

retworkx/namespace.py
Any package that imports `retworkx` (such as `qiskit-terra`) under `Python>=3.10` currently raises
```console
ImportWarning: RetworkxLoader.exec_module() not found; falling back to load_module()
```
Any system that uses `pytest` and sets the `filterwarnings` feature to `error` will fail loudly as a consequence of this (see, e.g., https://github.com/cda-tum/qcec/actions/runs/3394728729/jobs/5643660360#step:4:453).
`Loader.load_module()` has been deprecated since Python 3.4 (https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.load_module) and starting with 3.10, Python has started to actually raise the above `ImportWarning`.
This PR works around this issue by providing (rather straight-forward) implementations of the required `Loader.create_module()` and …
=> 🐛 Fix deprecated `Loader.load_module()`

releasenotes/notes/fix-sequence-protocol-e95246e864cc850a.yaml, src/iterators.rs, tests/rustworkx_tests/test_custom_return_types.py
Add the `sequence` option to PyO3's `pyclass`, so that the `sq_length` slot is implemented [1]. Implementing this method is required for sequence types, or Python C API functions like `PySequence_Size` will fail with an error.
The `reversed` built-in method relies on `PySequence_*` methods. A test reversing `NodeIndices` is added to guard against future violations of the sequence protocol.
Fixes #696.
[1]: https://github.com/PyO3/pyo3/pull/2567
=> Fix support of sequence protocol for returned lists

releasenotes/notes/fix-priority-queue-compat-48c22f64a9208812.yaml, rustworkx-core/src/connectivity/min_cut.rs
In priority-queue 1.3.0 compilation of rustworkx-core's min_cut module will fail because of the lack of a semicolon on the change_priority_by() call. This wasn't an issue with priority-queue 1.2.0 and for rustworkx development we are using priority-queue 1.2.0 because the priority queue 1.3.0 requires a rust version newer than our msrv. However, adding a semicolon to fix this compilation issue is also still compatibile with priority-queue 1.2.0. This commit does that to fix compatibility with newer versions of rustworkx-core that want to leverage the latest version of priority queue where they don't have the same MSRV constraints as rustworkx.
Fixes #744
=> Fix compatibility with priority-queue 1.3.0

.github/workflows/wheels.yml, Cargo.lock, Cargo.toml, docs/source/conf.py, docs/source/index.rst, releasenotes/notes/prepare-0.12.1-e59878f49351baf1.yaml, rustworkx-core/Cargo.toml, setup.py
This commit prepares for the 0.12.1 bugfix release. It bumps all the version numbers and adds a prelude release note to document the release. Once this merges we should tag the 0.12.1 release from that merged commit.
=> Prepare 0.12.1 release

.github/workflows/wheels.yml
This commit fixes the retworkx compat package publish job. The first issue is that the sdist for the retworkx package is not valid, we trigger the creation of the compat package by an env variable when calling setup.py/setuptools/builder/etc which triggers change the package name and other attributes. However if we create an sdist while setting the env variable this just bundles the setup.py and other source files in a tarball and when the sdist is installed rustworkx would be installed. So for the compat package we should only publish a pure python wheel that will have the actual compat shim. The other small change is switch the package to use python 3.10 instead of 3.7, which goes EoL in the near future.
=> Only publish wheel for retworkx compat package

releasenotes/notes/add_find_predecessor_node_by_edge-fcd525aff055c5fb.yaml, src/digraph.rs, tests/rustworkx_tests/digraph/test_edges.py
add function to get immediate predecessor of node by edge.
=> add find_predecessor_node_by_edge.

src/digraph.rs, src/graph.rs
The recent release of Rust 1.66.0 [1] added new on by default clippy rules which are causing failures when we run the clippy CI job with the new rust version. This commit updates the code to fix the issues that clippy has identified which will unblock CI.
[1] https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html
=> Fix clippy with Rust 1.66.0

rustworkx-core/src/generators/grid_graph.rs, rustworkx-core/src/generators/mod.rs, src/generators.rs
This PR migrates the grid_graph generator to rustwokx-core. It's based on https://github.com/Qiskit/rustworkx/pull/758.
=> Move grid_graph generator to rustworkx-core

rustworkx-core/src/generators/mod.rs, rustworkx-core/src/generators/petersen_graph.rs, src/generators.rs
This PR migrates the petersen_graph generator to rustwokx-core. It's based on https://github.com/Qiskit/rustworkx/pull/758.
=> Move petersen_graph generator to rustworkx-core

rustworkx-core/src/connectivity/find_cycle.rs, rustworkx-core/src/connectivity/mod.rs, src/connectivity/mod.rs
This PR moves the function `find_cycle` from `src/connectivity/mod.rs` to `rustworkx-core/connectivity/find_cycle.rs`.
=> Move find_cycle to rustworkx-core

docs/source/tutorial/betweenness_centrality.rst
Fix the warning in the docs because of [`matplotlib.cm`](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.7.0.html#deprecation-of-top-level-cmap-registration-and-access-functions-in-mpl-cm) deprecations
=> Fix Matplotlib warning when building docs

releasenotes/notes/fix-check-cycle-on-copy-d060a1781976f728.yaml, src/digraph.rs, tests/rustworkx_tests/digraph/test_copy.py, tests/rustworkx_tests/digraph/test_deepcopy.py
Adds `check_cycle` to `__getstate__` and `__setstate__` so that python copy and deepcopy should be exact duplicates of the original objects.
Expands the digraph copy and deepcopy tests to include `check_cycle` tests and python object instance tests.
Should resolve #836.
=> Implement `check_cycle` in `__getstate__` and `__setstate__`. Expand python copy tests.

Cargo.lock, Cargo.toml, src/graphml.rs
Closes #835 
Bumps `quick-xml` to 0.28 before the old version 0.22 stops being compiled by future Rust versions (as said in the warnings)
=> Bump `quick-xml` to 0.28

tests/retworkx_backwards_compat/digraph/test_dijkstra.py, tests/retworkx_backwards_compat/graph/test_all_simple_paths.py, tests/rustworkx_tests/digraph/test_dijkstra.py, tests/rustworkx_tests/generators/test_heavy_square.py, tests/rustworkx_tests/graph/test_all_simple_paths.py
This commit removes some stray debug print messages that were in some test files. This was causing spurious output that wasn't actionable during test runs both locally and in CI.
=> Remove stray debug prints from tests

docs/source/conf.py, docs/source/requirements.txt, tools/deploy_documentation_dev.sh, tox.ini
Tries to fix the same problem as #844 but without pinning
For some reason the `python3` kernel stopped being installed togethe with Jupyter, hence:
* we install the kernel on the tox environment
* we explicity use the kernel in the Sphinx configuration
=> Fix install and use of Jupyter Kernel for docs

tools/deploy_documentation.sh, tools/deploy_documentation_dev.sh
Similar to https://github.com/Qiskit/qiskit-aer/pull/1748, see https://github.com/Qiskit/qiskit.org/issues/3038 for more context
The Qiskit Ecosystem lives in qiskit.org/ecosystem and new place for qiskit related projects that are not technically Qiskit. This PR adds that destination for documentation deployment.
For now, a copy of the same docs in ecosystem would allow to have both q.o/documentation and q.o/ecosystem for testing that everything is fine. Once that's done, the CDN will redirects to the new location and the deploy to q.o/documentation can be removed.
=> deploy documentation in qiskit.org/ecosystem

tools/deploy_documentation.sh, tox.ini
This commit fixes two separate issues in the docs publishing job. The first is a failure that happens in the docs deployment on releases. The IFS (internal field separator) variable was getting set too broadly at the the level of the entire script instead of just the tag parsing. This was causing the passing of the secrets for decrypting the credential files to fail. This commit updates the IFS usage so it's not affecting the other commands after we split the tag version.
The second change is updating the default sphinx-build invocation to include the -d flag to change the default output directory for the .doctrees dir.
(see: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-d for details on the flag). The .doctrees dir is a local cache of pickle files for …
=> Fixup docs publish job

.github/workflows/docs_dev.yml, .github/workflows/docs_release.yml, .github/workflows/main.yml, tox.ini
Tox 4.0.0 was released in December 2022 [1] and was a major rewrite of the internals of the package that included numerous backwards incompatible changes [2]. Along with that major rewrite was a long period of instability in the package with a flurry of 47 releases [3] since 4.0.0 (which has only been 3-4 months). At the time of the 4.0.0 release we pinned the tox version in CI with #761 to avoid this instability as our tox configuration was not compatible with tox 4.x.y and tox was actually not compatible with how we had things configured more generally. The hope was that tox would stabilize more, fix the issues that plagued the tox 4 release series and we'd be able to relax that pin without requiring bumping our minimum tox version to ensure users could use either the old version or the …
=> Update tox configuration to use tox >= 4.4.0

rustworkx-core/src/centrality.rs
Closes #798 
I generated the values the test case is checking against using NetworkX. So the implementation is correct, it was just the test case and the `assert_almost_equal` that were incorrect
=> Fix incorrect `eigenvector_centrality` test case in `rustworkx-core`

README.md, docs/source/conf.py, rustworkx-core/src/lib.rs, setup.py
#873 reminded me of this. It is a minor change but it saves a redirect
=> Switch to new documentation links to avoid a redirect

setup.py, tox.ini
This commit updates the setup.py for the python package to add a new env variable `RUST_DEBUG` to force the package to be built in debug mode. By default pip install will build the rust code in release mode, which is the sane default you want for publishing or installing a package. But for local development you typically want to build normally in debug mode. This increases the build speed and also adds additional runtime checking to validate the code is fully working. The tradeoff with this though is the runtime is very poor because the compiler doesn't do any optimization.
As part of this commit the tox configuration is updated to default to debug builds. For unit tests the execution time is unchanged, because while it compiles faster that is offset by the slower execution of the tests. …
=> Add env variable to Python builds to force debug builds

releasenotes/notes/0.13/fix-removed-nodes-attr-d1829e1f4462d96a.yaml, src/digraph.rs, src/graph.rs, tests/rustworkx_tests/digraph/test_deepcopy.py, tests/rustworkx_tests/graph/test_deepcopy.py
This commit fixes an issue introduced by #589 where in certain cases node holes in a graph would result in a panic being raised. This was caused by a logic bug in trying to recreate the holes. Additionally, there were several places where graph methods removed nodes that the flag to indicate there were removals would no be set. This commit fixes all of these issues so that deepcopy/pickle works as expected.
=> Fix pickle/deepcopy node hole handling

rustworkx-core/src/token_swapper.rs
This PR adds a sort to the `todo_nodes` Vec in `token_swapper` in order to maintain deterministic output when using a seed. This problem appeared when implementing https://github.com/Qiskit/qiskit-terra/pull/10001 and some of the tests produced correct, but random output.
=> Add todo_nodes sort to maintain deterministic output in token_swapper

.github/workflows/wheels.yml, docs/source/install.rst, releasenotes/notes/s390x-tier-4-1701a0f044759cd1.yaml
This commit applies the various fixes needed to the wheel publishing job definitions for the 0.13.0 release. There were several jon errors during the release which were caused by various changes made to rustworkx, upstream dependencies, and CI environment since the 0.12.0 which caused issues during the release process. #753 should still be finished to simplify the job definitions, but that should be rebased to take this more targeted fix. The intent is for this to be a minimal diff for backporting to stable/0.13 for a future 0.13.1 release.
Of particular importance here though is the change in support tier for s390x from 3 to 4. This was caused by repeated issues with timeouts caused by running tests during the s390x linux wheel builds. To ensure we can reliably build the wheels this …
=> Apply wheel job fixes from 0.13.0 release

.github/workflows/main.yml
Recently github updated the cached version of python installed for 3.7 in the CI environment to 3.7.17. This new binary was not built with bz2 support which is causing failures in our CI jobs that run with 3.7. While we'll be dropping 3.7 support from the main branch (for 0.14.0) in the near future we still support 3.7 on the stable 0.13.x series. This commit pins the python version to the previous patch release which was known to work.
=> Pin Python version in CI

.github/workflows/main.yml, .github/workflows/wheels.yml, .mergify.yml, README.md, releasenotes/notes/drop-python-3.7-c71f8b6559beaf86.yaml, setup.py
As of `0.14.0`, Python 3.7 is no longer supported. This PR aims to prepare the CI and the rustworkx package setup to drop usage of Python 3.7 and work only with Python 3.8+.
=> Drop support for python 3.7 for 0.14.0

constraints.txt
Since the recent release of Pillow 10.0.0 the docs CI job has started failing due to an error in Pillow when trying to run the jupyter-execute cell in the `.to_dot()` docstring. It looks like a bug that was introduced in the new release which is being tracked in python-pillow/Pillow#7259 where it's trying to return a jpeg representation of the object from the RGBA data loaded from a PNG. Until the issue is resolved upstream in pillow this commit just caps the version we run in CI via the constraints file. While pillow is an optional dependency and we could cap the version in the extras, this issue isn't severe enough to warrant that, and the typical pillow usage, especially via the rustworkx api (i.e. graphviz_draw() which returns a PIL.Image object) will continue to work as expected with …
=> Pin pillow<10 in CI

rustworkx-core/src/connectivity/cycle_basis.rs
Because of a new Rust update, Clippy now warned for a line of code in `cycle_basis.rs` in `rustworkx-core`. This PR fixes that one line so that Clippy passes.
=> Adding Clippy Fix

.github/workflows/main.yml, rustworkx-core/Cargo.toml
This commit updates the version constraints on the hashbrown and indexmap dependencies in rustworkx-core's dependency list. These 2 dependencies are used for I/O to rustworkx-core and we previously had our versions set to the highest version compatible with the msrv. However, for users of rustworkx-core with newer MSRVs this limited version support caused issues if they wanted to use a newer version of these library (which was compatible with their MSRV) as an input or output to rustworkx-core. For example, as described in #911 qiskit-terra was using hashbrown 0.13.x and had errors because the released version of rustworkx-core only was listed as compatible with hashbrown 0.12. This version mismatch meant that the hashbrown objects created in qiskit-terra were not recognized by …
=> Relax constraints in rustworkx-core for hashbrown and indexmap

docs/source/index.rst, rustworkx-core/README.md
The main page explaining the rustworkx library in the Python docs previously didn't make any mention of rustworkx-core. While in general the Python side is built on top of rustworkx-core and the vast majority of the users of the Python library don't need to know about the pure Rust library inside, it is still good to highlight its existence in case anyone finds the Python library but is really interested in consuming it from Rust. This commit just adds a small subsection to the about page explaining the existence of rustworkx-core, its purpose, and where you can find mroe information about it.
=> Add a section to Python docs about page for rustworkx-core

Cargo.lock, Cargo.toml, docs/source/conf.py, releasenotes/notes/prepare-0.13.1-45317a1fda68b4ca.yaml, rustworkx-core/Cargo.toml, setup.py
This commit prepares the 0.13.1 release, this consists of bumping the version number to 0.13.1 in all the appropriate files. It also adds a prelude release note to provide a brief introduction to the release. When this commit merges it should be tagged as the 0.13.1 release.
Closes #893
TODO:
=> Prepare 0.13.1 release

Cargo.lock, Cargo.toml, rustworkx-core/Cargo.toml
This commit does two things: first, switch a lot of metadata-definition to use the workspace-package inheritance allowed since Rust 1.64 (including several shared dependencies); second, relax the installation requirements on `indexmap` and `hashbrown` to allow both to use their most recent two majors.  Dependents can then install `rustworkx-core` using either (say) `hashbrown 0.13.2` or `hashbrown 0.14.0` as desired, and similar between `indexmap 1.9.3` and `indexmap 2.0.0`.
This commit leaves the lock file in the `hashbrown 0.14.0`, `indexmap 2.0.0` state, although note that some other crate dependents still use `hashbrown 0.12.3` internally, but this doesn't matter for the public API surface.  I tested it manually in the `hashbrown 0.13.2`, `indexmap 1.9.3` state by updating those two …
=> Use workspace versioning and relax `hashbrown`/`indexmap` deps

tools/deploy_documentation.sh, tools/deploy_documentation_dev.sh
Follow up on https://github.com/Qiskit/rustworkx/pull/843
The documentation is correctly deployed in https://qiskit.org/ecosystem/rustworkx/ and the redirect is working. So, no need to upload to /documentation anymore.
=> remove deploy documentation to /documentation

.gitignore
When following the instructions in https://github.com/Qiskit/rustworkx#develop-mode after compilation I got a `.so` file not ignored by gitignore.
=> add .so files to gitignore

releasenotes/notes/handle-invalid-mapping-token_swapper-55d5b045b0b55345.yaml, rustworkx-core/src/token_swapper.rs, src/lib.rs, src/token_swapper.rs, tests/rustworkx_tests/test_token_swapper.py
This commit fixes the handling of invalid mapping requests in the token_swapper rustworkx-core function and the graph_token_swapper function in rustworkx that uses it. Previously if an invalid mapping was requested the function would internally panic because it always assumed there was a path in the graph to fulfill the user requested mapping. However, because the rustworkx-core function didn't support error returns a breaking api change is needed to add a result return type.
=> Handle token_swapper impossible swap mapping with Error

CONTRIBUTING.md, docs/source/conf.py, tests/retworkx_backwards_compat/visualization/test_graphviz.py, tests/retworkx_backwards_compat/visualization/test_mpl.py, tests/rustworkx_tests/visualization/test_graphviz.py, tests/rustworkx_tests/visualization/test_mpl.py, tools/deploy_documentation_dev.sh, tox.ini
Renaming some flags I found while working in #861
=> Rename old `RETWORKX` environment variables

.github/workflows/main.yml, tox.ini
Closes #982 
Make `stestr` have version greater than 4.1, containing the fix we need
=> Make `stestr` >= 4.1 

Cargo.lock
This bumps many of our dependencies, with highlights for:
* `indexmap` to 2.0.2 (replacing #987)
*  `hashbrown` to 0.14.1 (replacing #988)
More importantly, it compiles (which the previous PRs didn't for some reason)
=> Bump `indexmap` to 2.0.2, `hashbrown` to 0.14.1 & more

rustworkx-core/src/centrality.rs, src/dag_algo/mod.rs, src/matching/mod.rs, src/score.rs
The recent Rust 1.73.0 release introduced some changes to clippy's behavior that are causing failures in CI (and correctly calling out issues in our code). This commit updates the rustworkx source to correct these failures.
=> Fix build errors with Rust 1.73.0

rustworkx-core/src/token_swapper.rs
Fixes #994.
I believe that the function ``add_token_edges(node)`` should return ``Err(MapNotPossible {})`` when no mapping exists. This was already handled in the case that ``node`` had at least one neighbor.  Now I am also returning the error in the case a node has no neighbors.
=> mapping is not possible when a node has no neighbors

.github/workflows/main.yml, .github/workflows/wheels.yml, docs/source/install.rst, pyproject.toml, releasenotes/notes/platform-updates-e9b296144e633c95.yaml, setup.py, tests/retworkx_backwards_compat/graph/test_max_weight_matching.py, tests/rustworkx_tests/graph/test_max_weight_matching.py
As part of the 0.13.2 release we added support for Python 3.12 and musllinux to rustworkx. However, these changes did not happen on main yet. This commit applies the necessary changes to the main branch for the 0.14.0 and future releases. Also to simplify the configuration of the cibuildwheel jobs this combines #753 into this PR so that the configuration is centralized in the pyproject.toml.
=> Add support for Python 3.12 and musllinux to main

releasenotes/notes/add-isolates-edc5da3a3d8fb4fd.yaml, rustworkx-core/src/connectivity/isolates.rs, rustworkx-core/src/connectivity/mod.rs, rustworkx/__init__.py, src/connectivity/mod.rs, src/lib.rs, tests/rustworkx_tests/digraph/test_isolates.py, tests/rustworkx_tests/graph/test_isolates.py
This commit adds a new function, isolates(), which is used to find all the isolates in a graph.
=> Add isolates() function to rustworkx

docs/source/api/random_graph_generator_functions.rst, releasenotes/notes/add-albert-graph-5a7d393e1fe18e9d.yaml, rustworkx-core/src/generators/mod.rs, rustworkx-core/src/generators/random_graph.rs, src/lib.rs, src/random_graph.rs, tests/rustworkx_tests/test_random.py
This commit adds new random graph functions to rustworkx and rustworkx-core to implement a random graph generator using the Barabási–Albert preferential attachment method. It takes an input graph (defaulting to a star graph) and then extends it to a given size.
=> Add barabasi_albert_graph random graph functions

releasenotes/notes/numpy-2-pin-11bc3a379fb29bf7.yaml, setup.py
We have compiled extensions that are built against the Numpy C API. The Numpy transition guide for developers of downstream packages[1] encourages us to put in this pin until we have wheels built against the newer version, which is not expected to be fully ABI compatible (but extensions built against Numpy 2 _should_ work with older versions of Numpy).
Note that this won't prevent package managers from resolving _older_ versions of rustworkx (which don't have the pin) along with Numpy 2, but there's not a vast amount we can do about that now.
=> Pin Numpy < 2 in requirements

releasenotes/notes/fix-all-simple-paths-03f4534438d1068d.yaml, src/connectivity/mod.rs, tests/rustworkx_tests/digraph/test_all_simple_paths.py, tests/rustworkx_tests/graph/test_all_simple_paths.py
=> fix `all_simple_paths`

.github/workflows/wheels.yml, docs/source/install.rst, releasenotes/notes/platform-updates-e9b296144e633c95.yaml
Follow up to #992 and #997
This adds support for musl aarch64 wheels.  
The wheels are unstested because of QEMU and NumPy. QEMU takes around 30+ minutes per Python version to build rustworkx.  NumPy doesn't provide wheels for this architecture, hence adding tests would balloon the time considerably just to compile NumPy.
After #891, we can improve this architecture support by adding tests
=> Add musl aarch64 support at tier 4

rustworkx-core/src/shortest_path/dijkstra.rs, src/score.rs
Some minor improvements suggested by clippy. They are currently blocking all CI actions
=> Fix clippy findings for Rust 1.74

tox.ini
The API reference autosummary stubs are in `docs/source/apiref`, rather than loose in `docs/apiref`.
=> Fix `docs-clean` tox job

docs/source/api/algorithm_functions/shortest_paths.rst, docs/source/api/pydigraph_api_functions.rst, docs/source/api/pygraph_api_functions.rst, rustworkx/shortest_path.pyi, src/digraph.rs, src/lib.rs, src/shortest_path/floyd_warshall.rs, src/shortest_path/mod.rs, tests/rustworkx_tests/digraph/test_floyd_warshall.py, tests/rustworkx_tests/graph/test_floyd_warshall.py
This PR adds "next node" matrix to the Floyd-Warshall implementations' return value.
This helps re-construct the shortest path from the result.
`digraph_floyd_warshall_numpy` and `graph_floyd_warshall_numpy` return **two** variable by applying this patch. In recent version, they returned only a length table.
The next node table is inherently dense, even though the graph is sparse. To not break the advantage of the implementation optimized for the sparse graph, I modified only numpy variants.
=> Save next nodes in Floyd-Warshall numpy variants for path reconstruction

rustworkx/visualization/matplotlib.py
The `np.alltrue` method will be removed in numpy 2.0.
=> Replace call to deprecated np.alltrue with np.all

.github/workflows/main.yml, rustworkx-core/src/centrality.rs, rustworkx-core/src/coloring.rs, rustworkx-core/src/connectivity/all_simple_paths.rs, rustworkx-core/src/connectivity/biconnected.rs, rustworkx-core/src/connectivity/chain.rs, rustworkx-core/src/connectivity/conn_components.rs, rustworkx-core/src/connectivity/core_number.rs, rustworkx-core/src/connectivity/cycle_basis.rs, rustworkx-core/src/connectivity/find_cycle.rs, rustworkx-core/src/connectivity/isolates.rs, rustworkx-core/src/line_graph.rs, rustworkx-core/src/token_swapper.rs, rustworkx-core/tests/centrality.rs, rustworkx-core/tests/planar.rs, rustworkx-core/tests/test_connectivity.rs
configures the clippy CI job to run on all targets and addresses all existing `clippy::all` errors and warnings
=> run clippy CI job on all targets

.github/workflows/docs_dev.yml, .github/workflows/docs_release.yml, .github/workflows/main.yml, .github/workflows/wheels.yml
This PR is to address some of the warnings that started showing up, like the following one:
```
[Build, rustfmt, and python lint]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: 
actions/checkout@v3, actions/setup-python@v4, actions/upload-artifact@v3. 
For more information see: 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
=> Bump Github Actions version to silence Node.js version warnings

pyproject.toml, tox.ini
This fixes the `lint` job for `tox>=4`, which uses `whitelist_externals` is removed in favour of `allowlist_externals`.  This also makes the `lint` and `black` runs skip installation of the package, which makes them much faster to use while making changes, and these are static analysis tools, so don't need to install.
=> Improve ergonomics of `tox` lint jobs

docs/source/benchmarks.rst, docs/source/networkx.rst
I made some minor typo and clarity fixes as I was going through the tutorials (no meaning or conceptual changes). Hope this works!
Also, many thanks for publishing this library and for documenting it so well! Really looking forward to using it more.
=> Docs: typo and clarity updates

src/iterators.rs
Flipping the order of `Slice` and `Int` in `SliceOrInt` so that `Int` comes first means that the `FromPyObject` derivation will then try `Int` first, which is the correct variant in like 99.9% of uses of the struct. This has the impact of improving int `__getitem__` times in the custom iterators by about 3x (from 205ns to 61ns on my machine), which has knock-on effects for the implicit iterators Python defines for these classes.
This implements the performance improvement I mentioned in https://github.com/Qiskit/rustworkx/issues/1090#issuecomment-1954836685.  I can also look into defining manual Python-space iterators (rather than using the implicit one based on `__getitem__`), if that's an interesting path - I haven't tried it yet, so I don't know if there's more performance to be had.
=> Improve performance of custom-iterator `__getitem__`

.mergify.yml
In #1070 we updated the version numbers of rustworkx to indicate the main branch is developing the next release. However, in that PR we neglected to update the mergify backport branch. This means when we tag a PR to main as stable backport potential mergify will incorrectly backport the PR to stable/0.13 instead of stable/0.14. This commit corrects this oversight and updates the mergify config to backport to the correct branch.
=> Fix backport branch post 0.14.0 release

.github/workflows/wheels.yml
This commit fixes an issue in the ppc64le wheel builds. One of the two ppc64le wheel build jobs was incorrectly attempting to build wheels for musl environments which isn't a supported platform and the jobs failed to configure. This commit just adds the missing skip for those environments to the job configuration to fix this issue.
=> Add missing musl skip for ppc64le builds

Cargo.lock, Cargo.toml, docs/source/conf.py, releasenotes/notes/prepare-0.14.1-e5065553a44eb035.yaml, setup.py
This commit prepares for a 0.14.1 release which just includes #1109 to fix ppc64le builds and #1096 to fix the overhead of `__getitem__` on custom sequence return types.
=> Prepare 0.14.1 release

README.md
Changes:
- Moves project history toward the bottom of the page to make it clearer that Rustworkx is freestanding and has utility beyond just Qiskit.
- Moves usage upwards, since this is often how new potential users will evaluate how well the library will suit their needs.
- Move project description upward so it's easier to see, and make it a bit more concise.
=> Reorder and tweak README.md sections

releasenotes/notes/fix-panic-3962ad36788cab00.yaml, src/shortest_path/mod.rs, tests/digraph/test_astar.py, tests/digraph/test_bellman_ford.py, tests/digraph/test_dijkstra.py, tests/graph/test_astar.py, tests/graph/test_bellman_ford.py, tests/graph/test_dijkstra.py, tests/graph/test_max_weight_matching.py
In #1117 is presented the presence of an uncaught `pyo3.PanicException` when the index of the source node is no out of bound in the graph. With this naive approach i try fix this issue raising a more understandable `IndexError`.
=> Fix panic error at shortest paths 

src/iterators.rs
Fixed a couple of typos in the doc string of `NodeIndices`.
=> Fix typo in docs of `NodeIndices`

releasenotes/notes/graphml-long-type-support-05e66d139e685dfe.yaml, src/graphml.rs, tests/test_graphml.py
Fixes #1140 by adding GraphML support for "long", along with corresponding unit tests
=> Adds support GraphML support for long

.github/workflows/main.yml
This updates the Coveralls Github Action to use v2. This automatic update slipped through the cracks because we use the released version in the `master` branch while development has moved to the `main` branch.
This will also fix the warnings about using Node.js version 16 which will be removed by Github sometime
=> Update Coveralls Github Action

constraints.txt
The recent lxml 5.2.0 release is raising an exception about a packaging change that moved a submodule into a different location during the docs build. We don't actually directly use lxml in rustworkx (or the docs), but it gets pulled in via a dependency of jupyter-sphinx (it's deeper in the dependency tree than jupyter-sphinx's immediate dependencies). To workaround this until things are updated to take this into account this commit pins the lxml version in the constraints.txt file so we don't pull in the latest release.
=> Pin lxml in constraints

tests/visualization/test_graphviz.py
With recent graphviz releases the graphviz_draw() visualization tests for 50 node random graphs were taking an inordinate amount of time. This didn't seem to be an issue in CI but on my local system with graphviz 10.0.1 the time for graphviz to generate a visualization for the 50 node random graph was orders of magnitude slower than the rest of the tests in the rustworkx python tests. This commit decreases the graph size to only be 10 nodes, which reduces the runtime of these tests to be inline with expectations.
=> Decrease graphviz visualization test size to speed up tests

.github/workflows/main.yml, Cargo.lock, Cargo.toml, README.md, releasenotes/notes/bump-msrv-170-f1518d5adb41f7c3.yaml, rustworkx-core/README.md
This commit bumps the MSRV for rustworkx in 0.15.0 to 1.70.0. This enables us to use GATs (see #1143) and also enables to update some of our dependencies which require newer versions of rust to compile.
=> Bump MSRV to 1.70

releasenotes/notes/initial-topo-cd502f3140500f93.yaml, rustworkx/rustworkx.pyi, src/dag_algo/mod.rs, src/toposort.rs, tests/digraph/test_nodes.py, tests/digraph/test_toposort.py
This adds a way for the topological sorters to recieve a set of initial nodes to begin the search from.  This can allow the topological iteration to begin from a mid-point of the order, or to simply provide Rustworkx with the already-known set of initial nodes, skipping the iteration over each node to find the full set.  Especially in `TopologicalSorter`, where one may be using the on-line search to find only the first handful of nodes in the topological order in an inner loop of a mutating graph, this can be a complexity improvement.
The `initial` nodes are required to have no topological ordering between themselves, and it is an error if they do.  There are other possible conventions to choose here, but this one is the easiest to state / understand and the fastest to execute; most other …
=> Add `initial` argument to topological sorters

.github/workflows/main.yml, .github/workflows/wheels.yml
Github actions recently changed the macos-latest runner to use macos-14, which changes the CI environment to run with arm64 instead of x86_64. This has several impacts on our test jobs where the intent was to specifically test native x86_64 macOS. This commit changes the ci configuration to use macos-13 in places where this was the case, as we were already explicitly using macos-14 where we wanted arm64 runners.
=> Avoid using macos-latest for jobs we want x86_64 macOS

releasenotes/notes/fix-mpl-draw-kargs-typing-6cf7cfde0db072d5.yaml, rustworkx/visualization/matplotlib.pyi
Closes #1179 
We missed https://typing.readthedocs.io/en/latest/spec/typeddict.html#totality. Because `total=True` is the default, `mypy` and other type checkers expect all arguments which is not user-friendly.
=> Allow partial kwargs in mpl_draw

releasenotes/notes/fix-digraph-find-cycle-141e302ff4a8fcd4.yaml, rustworkx-core/src/connectivity/find_cycle.rs, tests/digraph/test_find_cycle.py
Closes #1171 
Instead of picking an arbitrary node if it is not provided, we find a smarter pick that is in a strongly-connected component with more than one node. It also handles the case of self-loops in case there is a SCC with a single node.
=> Always return a cycle in `digraph_find_cycle` if no node is specified and a cycle exists

.github/workflows/main.yml
I have no idea why but our Coveralls integration started complaining about `lcov` files with `.info`, so I switched to `.lcov`
=> Fix `coveralls` by changing the extension to `.lcov`

.github/workflows/main.yml, releasenotes/notes/lexicographical-topo-sort-core-e85fba409d612600.yaml, rustworkx-core/src/dag_algo.rs, src/dag_algo/mod.rs
This commit adds a rust generic implementation of the lexicographical topological sort function that was previously only exposed via the python interface to rustworkx-core. This new function is used internally by rustworkx and replaces the python specific implementation that used to be there. But it now exposes an interface to use it to rust.
Fixes: #1165
=> Add lexicographical_topological_sort function to rustworkx-core

releasenotes/notes/bfs-pred-succ-rustworkx-core-480d25a374294899.yaml, rustworkx-core/src/traversal/mod.rs, src/traversal/mod.rs
This commit adds an implementation of the bfs_successors and bfs_predecessors functions to the rustworkx-core crate exposing the functions to rust users. The existing implementation in the rustworkx crate is removed and it is updated to call the rustworkx-core functions. The rustwork-core functions return an iterator of nodes indices and the Python crate side consumes the iterator to build the bfs view these functions previously returned.
=> Move bfs_successors and bfs_predecessors to rustworkx-core

rustworkx-core/src/connectivity/biconnected.rs, rustworkx-core/src/connectivity/chain.rs, rustworkx-core/src/generators/random_graph.rs, rustworkx-core/src/planar/lr_planar.rs, rustworkx-core/src/steiner_tree.rs, src/connectivity/johnson_simple_cycles.rs, src/iterators.rs, src/layout/spring.rs, src/random_graph.rs, src/shortest_path/floyd_warshall.rs, src/shortest_path/mod.rs
Currently CI is broken because Clippy introduced new lints in the 1.79 update. This PR fixes that
=> Fix Clippy warnings due to 1.79

.github/workflows/main.yml, noxfile.py, tox.ini
With the release of Python 3.12.1 we stopped using stest in CI because 3.12.1 introduced a breaking API change to the unittest runner API that broke a dependency of stestr, testtools. This has been worked around with a new testtools release so we can restore using stestr in CI again which should improve test run throughput. This commit restores using stestr for the test CI jobs and local runs. The cibuildwheel config remains unchanged and uses the stdlib unittest runner still, just for simplicity so we don't need to install additional test dependencies.
=> Use stestr again for unittests

tests/digraph/test_is_semi_connected.py, tests/graph/test_coloring.py, tests/graph/test_max_weight_matching.py, tests/visualization/test_graphviz.py
This is mostly miscellaneous improvements that are not related:
* Started using sub-tests with tests from #1203
* Reduced graph input size from 2500 to 100 nodes for one test case from #1215. It seemed excessive to run Floyd-Warshall with that many nodes to compare
* Remove print statements that are not necessary and show up in CI
=> Miscellaneous test improvements

releasenotes/notes/fix-graphviz-escaping-39a2d1cebb586eca.yaml, src/dot_utils.rs, tests/digraph/test_dot.py, tests/graph/test_dot.py, tests/visualization/test_graphviz.py
This commit fixes a regression introduced in #1203. That PR was attempting to fix missing character escaping in some string fields but it was doing so too eagerly. This would result in invalid dot files being produced for users upgrading from rustworkx < 0.15.0 that were wrapping strings in quotes as needed previously. For example if you were setting `'color="#aaaaaa"'` previously before this would become `color="\"#aaaaaa\""` after #1203. In order to quickly release a 0.15.1 this commit reverts the dot generation component of #1203 but updates the code to wrap tooltip in addition to label which was what the original bug reported. In 0.16.0 we should investigate adding a flag to control the escaping behavior of the function to either decide to wrap values in quotes or not.
=> Fix dot file generation

releasenotes/notes/hexagonal-lattice-graph-fixes-1cd4aa88f1591701.yaml, rustworkx-core/src/generators/hexagonal_lattice_graph.rs, src/generators.rs, tests/generators/test_hexagonal.py
Follow-up to #1213.
* Addressed comments on the previous PR
* Split tests with a lot of sub-cases into subtests
* Removed unnecessary module
* We now pre-compute the number of edges in each graph, so that we can call `G::with_capacity(self.num_nodes, self.num_edges)` to create the graph where before we had `G::with_capacity(self.num_nodes, self.num_nodes)`
* Fixed two bugs in the position calculation
* In my initial implementation I missed a factor of two, so the hexagons were not actually regular
* For lattices with an odd number of columns, the node index arithmetic had an error that led to configurations like this:
Probably the reason I missed this is that I mostly wrote tests for cases with an even number of columns (required when `periodic = True`). We now get the expected result:
=> Hexagonal lattice followup

rustworkx-core/src/dag_algo.rs, rustworkx-core/src/steiner_tree.rs
This is to unblock CI for the future backports of #1246 and #1247. The lints were super simple this time, we only changed docstrings not code.
=> Fix Clippy warnings on stable/0.15 branch

.github/workflows/docs_dev.yml, .github/workflows/docs_release.yml, .github/workflows/main.yml, .github/workflows/wheels.yml, .mergify.yml, Cargo.toml, constraints.txt, noxfile.py, pyproject.toml, releasenotes/notes/py38-eol-6443a548b6c727cc.yaml, rustworkx/__init__.pyi, rustworkx/generators/__init__.pyi, rustworkx/rustworkx.pyi, rustworkx/visualization/matplotlib.pyi, setup.py, tests/graph/test_max_weight_matching.py, tests/graph/test_planar.py, tests/test_graphml.py, tests/test_token_swapper.py, tests/visualization/test_mpl.py, tox.ini
This is our yearly Python version maintenance. 3.8 reached EOL. I will add the newly released 3.13 in a separate PR to test the wheel release etc.
I profited to update `black`, `ruff` and `mypy` as well. `mypy` passes without any changes, but there were some minor differences with `black` and `ruff`.
=> Remove support for Python 3.8

src/iterators.rs
I found that rustworkx's custom vectors do not provide `__repr__` method, which I have to use `print(indices)`
=> Impl `__repr__` for custom vector

releasenotes/notes/correct-edge-colors-e082e1761e1c060b.yaml, rustworkx/visualization/matplotlib.py
Closes #1308. A bit embarrasing but we let that slip through in #1204.
The solution is a bit hacky but reusing Python dictionaries was the easiest way to get a set-like object that preservers iteration order.
=> Fix bug where edge colors are randomly shuffled in `mpl_draw`

releasenotes/notes/fix-1331-2806958e91e1be30.yaml, rustworkx-core/src/generators/star_graph.rs, rustworkx-core/src/token_swapper.rs, src/dag_algo/mod.rs, src/digraph.rs, src/graph.rs, src/iterators.rs, src/lib.rs
=> Fix clippy for Rust 1.83

.github/workflows/main.yml, rustworkx-core/src/centrality.rs, rustworkx-core/src/generators/dorogovtsev_goltsev_mendes_graph.rs, rustworkx-core/src/steiner_tree.rs
Fix the warnings during the `rustworkx-core` documentation build. See e.g. [this job](https://github.com/Qiskit/rustworkx/actions/runs/12091031005/job/33718904317#step:14:72):
```
warning: unresolved link to `1`
--> rustworkx-core/src/generators/dorogovtsev_goltsev_mendes_graph.rs:19:60
|
19 | /// Generate a graph following the recursive procedure in [1].
|                                                            ^ no item named `1` in scope
|
= help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
= note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
warning: unresolved link to `1`
--> rustworkx-core/src/generators/dorogovtsev_goltsev_mendes_graph.rs:46:9
|
46 | /// .. [1] S. N. Dorogovtsev, A. V. Goltsev and J. F. F. Mendes
|         ^ no item named …
```
=> rustworkx-core: fix docs build warnings

Cargo.toml, rustworkx-core/src/dag_algo.rs
[In short the new clippy lint suggests us to replace `map_or` with `is_none_or`.](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or)
But `is_none_or` is only available for Rust 1.82 or newer (https://doc.rust-lang.org/std/option/enum.Option.html#method.is_none_or). So we can revisit this but at the time it is best to ignore
=> Silence rust clippy lint enabled after the 1.84 release

Cargo.lock, Cargo.toml, src/cartesian_product.rs, src/coloring.rs, src/connectivity/mod.rs, src/dag_algo/mod.rs, src/digraph.rs, src/generators.rs, src/graph.rs, src/graphml.rs, src/iterators.rs, src/json/mod.rs, src/json/node_link_data.rs, src/lib.rs, src/random_graph.rs, src/shortest_path/mod.rs, src/steiner_tree.rs, src/tensor_product.rs, src/toposort.rs
Closes #1325 
This commit bumps the version of pyo3 and rust-numpy used by qiskit to the latest release 0.23. The largest change by volume of code is the deprecation of all the *_bound() methods. These are just warnings but they would be fatal to our CI so it needs to be updated. The larger functional change that required updating the code is the change in the traits around converting to Python objects.
As a side effect of this change it lets us unify the hashbrown versions installed because we can update indexmap.
=> Bump PyO3 and rust-numpy to 0.23

.github/workflows/main.yml, Cargo.lock, Cargo.toml, README.md, releasenotes/notes/bump-msrv-179-b3732d9b786dc265.yaml, rustworkx-core/README.md
This bumps our MSRV to a newer Rust version and aligns the MSRV of rustworkx with Qiskit. https://github.com/Qiskit/qiskit/pull/13709 was the bump in Qiskit's side.
There is nothing tying us to 1.70 and now that we released a new major version I think it is fair to use newer a `rustc` as the next release doesn't have a specified date yet.
=> Bump MSRV to 1.79

.github/workflows/wheels.yml, pyproject.toml
Closes #1367 
In hindsight we should have used this before the release as the QEMU jobs are really unstable. I might need to backport this to the 0.16 branch and trigger a workflow again.
This is a copy of https://github.com/Qiskit/qiskit/pull/13682. I will test it in my branch and check it works.
=> Use native aarch64 GitHub Action workers

CONTRIBUTING.md, README.md, docs/source/install.rst, docs/source/networkx.rst, docs/source/release_notes.rst, docs/source/tutorial/dags.rst, docs/source/tutorial/introduction.rst, rustworkx-core/README.md, rustworkx/__init__.py, src/centrality.rs, src/connectivity/mod.rs, src/dag_algo/mod.rs, src/digraph.rs, src/graph.rs, tests/graph/test_max_weight_matching.py, tests/graph/test_steiner_tree.py
Fix some repeated words, it's/its, and a few typos.
=> Fix some typos in docs

src/graph.rs
As a beginner in rustworkx, when I followed the API docs, sometimes I was not quite sure whether the argument or the return value was the int node indices or the attached objects.
Unfortunately it looks like it is not possible to add Python type hints to the PyO3 signatures. Therefore I reviewed the src/graph.rs and added them wherever possible in the docstrings. I also tried to consolidate the description of the same parameters across the functions.
If this is a good way to go, I'll be happy to tackle the rest of the docstrings in the near future.
=> Consolidate Python docstrings in graph.rs

releasenotes/notes/fix-search-panic-fd54b704f7ee2101.yaml, src/traversal/mod.rs, tests/digraph/test_bfs_search.py, tests/digraph/test_dfs_search.py, tests/digraph/test_dijkstra_search.py, tests/graph/test_bfs_search.py, tests/graph/test_dfs_search.py, tests/graph/test_dijkstra_search.py
Closes #1386 
I opted to check at the Python level because it seemed simpler to handle the failures before calling `rustworkx-core`.
=> Fix `bfs_search` and other search methods panicking with invalid sources

releasenotes/notes/fix-ancestors-panic-3c64b9b43bb0551a.yaml, src/traversal/mod.rs, tests/digraph/test_ancestors_descendants.py
Closes #1381 
This is conceptually very similar to #1388 so I might need to go over the whole traversal module looking for what methods panic with this kind of input.
=> Fix panic for `ancestors` and `descendants` when the source node is invalid

src/connectivity/mod.rs
This should help new users to discover related methods and understand the method signature with simple examples. I believe there's enough space on the API docs website for more material.
I didn't find the following methods: `number_strongly_connected_components`, `is_strongly_connected`, `number_semi_connected_components`, and `semi_connected_components`. Otherwise I'd like to cross-reference them in the related docstrings.
Also I found it a bit confusing that `connected_components` and `weakly_connected_components` return a list of sets, whereas `strongly_connected_components` returns a list of lists, although the concept is similar.
OT: Did you actually consider using pytest for tests?
=> Extend docstrings for some graph connectivity methods

src/digraph.rs
The inability to find the desired index in the subgraph was unexpected. This behavior, if it is a feature rather than a bug, needs to be documented.
=> docs: add a note that subgraph recreates indexes

src/digraph.rs, src/traversal/mod.rs, tests/digraph/test_pred_succ.py
I realized the `ancestors` and `descendants` raise an `IndexError` if the provided node is not present in the directed graph. On the other hand `predecessors` and `successors`, which are quite similar methods, just return an empty list.
I do not want to introduce a breaking change, so I just added a test pair to make sure this persists.
Also for the formatting, I discovered the docs website was using [Furo](https://pradyunsg.me/furo/reference/admonitions/) which offers some nice details to distinguish different parts of a method documentation. Before we have lots of docs, we'll have to find some useful and decent style.
=> Enhance docs and tests for pred/succ/anc/desc

rustworkx-core/src/dag_algo.rs, rustworkx-core/src/graph_ext/contraction.rs, rustworkx-core/src/shortest_path/astar.rs, rustworkx-core/src/traversal/dijkstra_visit.rs, src/digraph.rs
This just consolidates the usage of `hashbrown::hash_set::Entry` across the project (except the changes done in #1405).
=> Consolidate the hashset/match syntax

rustworkx-core/src/bipartite_coloring.rs, rustworkx-core/src/centrality.rs, rustworkx-core/src/coloring.rs, rustworkx-core/src/connectivity/cycle_basis.rs, rustworkx-core/src/connectivity/find_cycle.rs, rustworkx-core/src/dag_algo.rs, rustworkx-core/src/generators/barbell_graph.rs, rustworkx-core/src/generators/binomial_tree_graph.rs, rustworkx-core/src/generators/complete_graph.rs, rustworkx-core/src/generators/cycle_graph.rs, rustworkx-core/src/generators/full_rary_tree_graph.rs, rustworkx-core/src/generators/grid_graph.rs, rustworkx-core/src/generators/heavy_hex_graph.rs, rustworkx-core/src/generators/heavy_square_graph.rs, rustworkx-core/src/generators/hexagonal_lattice_graph.rs, rustworkx-core/src/generators/karate_club.rs, rustworkx-core/src/generators/lollipop_graph.rs, rustworkx-core/src/generators/path_graph.rs, rustworkx-core/src/generators/petersen_graph.rs, rustworkx-core/src/generators/random_graph.rs, rustworkx-core/src/generators/star_graph.rs, rustworkx-core/src/line_graph.rs, rustworkx-core/src/max_weight_matching.rs, rustworkx-core/src/token_swapper.rs, rustworkx-core/src/traversal/dfs_edges.rs
Mostly about https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items
There was also https://rust-lang.github.io/rust-clippy/master/index.html#manual_div_ceil
=> Fix clippy warnings for Rust 1.86

Cargo.lock, Cargo.toml, rustworkx-core/Cargo.toml
This PR is a bunch of updates. It looks like dependabot hasn't been runing as much lately, we might need to investigate.
In order of priority:
* PyO3 -> 0.24, biggest change; fortunately not a big refactor
* petgraph -> 0.7.1, removes some constraints on indexmap
* rayon-cond -> 0.4, minor change but it bumps itertools with it
=> Update PyO3 to 0.24 and more

src/digraph.rs, src/graph.rs, src/lib.rs
Follow up of #1348 
Since #1415, we have PyO3 0.24 that contains https://github.com/PyO3/pyo3/pull/4917 which will make `__clas_geitem__` slightly simpler and faster
=> Use `PyGenericAlias` from PyO3 instead of importing `types.GenericAlias`

.github/workflows/main.yml, CONTRIBUTING.md, rustworkx-core/src/bipartite_coloring.rs, rustworkx-core/src/coloring.rs, rustworkx-core/src/connectivity/johnson_simple_cycles.rs, rustworkx-core/src/dag_algo.rs, rustworkx-core/src/generators/hexagonal_lattice_graph.rs, rustworkx-core/src/generators/random_graph.rs, rustworkx-core/src/line_graph.rs, rustworkx-core/src/traversal/mod.rs
Right now, if one runs `cargo clippy --all-targets` inside the `rustwork-core` directory, it will find lints from clippy. Sure, they are for tests, but they are still lints.
To address that, in this PR I:
* Fixed the findings from the lints
* Transitioned to running the lint with `cargo clippy --workspace` which does include the tests
* Updated `CONTRIBUTIGNG.md` and CI to stop having to run commands inside the `rustworkx-core` directory. For most cases, `cargo` provides commands that work with all workspace crates at the root
=> Fix `cargo clippy` not covering `rustworkx-core` tests

docs/source/api/exceptions.rst, src/lib.rs
The [exceptions API](https://www.rustworkx.org/api/exceptions.html) was quite empty and since PyO3 [allows](https://github.com/PyO3/pyo3/pull/2027) adding docstrings to `create_exception`, I moved the comments to docstrings and also completed and sorted alphabetically their list in the API docs.
=> Add docstrings to exceptions and sort their list alphabetically

Cargo.lock, Cargo.toml, releasenotes/notes/bump-petgraph-79f354e3dce1aa14.yaml, rustworkx-core/src/graph_ext/mod.rs, src/connectivity/mod.rs
This commit bumps the petgraph version used in rustworkx to the latest release 0.8.1. This is technically an api change for rustworkx-core as some of the generics (mostly around MatrixGraph) changed, but also because now when building rustworkx-core only petgraph 0.8.1 objects are accepted and older releases are no longer compatible with rustworkx-core. This is not generally an issue if you use the rustworkx-core petgraph re-export at ``rustworkx_core::petgraph``, but as 0.8.1 does contain some api changes users will need to account for those when upgrading to rustworkx-core 0.17.0.
=> Bump petgraph to 0.8.1

rustworkx-core/fuzz/Cargo.toml, rustworkx-core/fuzz/fuzz_targets/test_fuzz_bellman_ford.rs
Added a check to test the principle that for undirected non-negative weights, Bellman Ford and Dijkstra's algorithm must produce the same shortest distance.
Next, will start on adding fuzz targets for connectivity and generator modules.
=> Adding Bellman Ford Fuzz targets

.github/workflows/wheels.yml
Closes #1432 
In short, this incorporates https://github.com/pypa/cibuildwheel/issues/2305 which fixes our issue in i686 builds
Test build: https://github.com/IvanIsCoding/rustworkx/actions/runs/14562751655
=> Update cibuildwheel to 2.23.2 in order to unblock i686 builds

rustworkx-core/fuzz/Cargo.toml, rustworkx-core/fuzz/fuzz_targets/test_fuzz_contraction.rs
Added a fuzz target for cycle check validation and idempotency check (calling contract_nodes twice doesn't crash).
=> Adding fuzz target for contraction

rustworkx-core/fuzz/Cargo.toml, rustworkx-core/fuzz/fuzz_targets/test_fuzz_centrality.rs
Added a fuzz target for closeness centrality with wf_improved = true and false.
Both parallel and sequential modes (parallel_threshold = 1 and 200).
Consistency check between parallel and sequential outputs for each wf_improved mode.
=> Adding fuzz target for centrality

pyproject.toml, rustworkx-core/src/generators/random_graph.rs, tests/digraph/test_node_link_json.py, tests/graph/test_node_link_json.py
This PR is a collection of minor things:
* Removes the `fixtures` test dependency. I don't know when we stopped using it but it seems it can go
* Fixes a warning from NetworkX that I noticed in https://github.com/Qiskit/rustworkx/pull/1440#issuecomment-2858445887.  Our tests would start failing with NetworkX 3.6.
* Fixes a typo that makes `nox -elint` fail
* Pins `ruff`. Right now, we have `ruff~=0.6`. But `ruff` has not achieved a major version yet, so this is essentially running the latest version!
=> Minor improvements: prevent future test failures, remove `fixtures`, and more

rustworkx-core/tests/quickcheck/barbell_graph.rs, rustworkx-core/tests/quickcheck/main.rs
This QuickCheck test verifies structural properties of barbell_graph.
It ensures the total number of nodes is 2 × mesh_size + path_size.
It checks the number of edges matches the expected sum of two cliques, path edges, and connectors.
=> Adding quickcheck for barbell graphs

rustworkx-core/tests/quickcheck/cycle_graph.rs, rustworkx-core/tests/quickcheck/main.rs
We are testing the structural property of cycle graph by ensuring:
Node count is exactly n
Edge count is:
n for directed, non-bidirectional
2n for directed, bidirectional
n for undirected
All expected edges are present
In bidirectional mode: for every (u, v) edge, there’s also a (v, u) edge
=> Adding Quickcheck for cycle graph

rustworkx-core/tests/quickcheck/dorogovtsev_goltsev_mendes_graph.rs, rustworkx-core/tests/quickcheck/main.rs
Added quickcheck to test the structural properties of DGM graph, by checking its number of edges and nodes.
=> Adding Quickcheck for DGM graph

releasenotes/notes/port-transitivity-c69b72f813e68693.yaml, rustworkx-core/src/lib.rs, rustworkx-core/src/transitivity.rs, src/transitivity.rs
This ports the undirected graph and directed graph transitivity functions to rustworkx-core (#1121).
While this is mostly a copy and paste, I changed for loops to iterators and `HashSet::remove` for a `filter` when constructing the set.
I think the functions `digraph_node_triangles` and `graph_node_triangles` that count the triangles of a vertex could be part of the public API. Implementing the [local clustering](https://en.wikipedia.org/wiki/Clustering_coefficient#Local_clustering_coefficient) is direct using these functions while it doesn't seem part of rustworkx right now.
=> Port transitivity to rustworkx-core

rustworkx-core/tests/quickcheck/main.rs, rustworkx-core/tests/quickcheck/path_graph.rs
Checking node count, edge count, no self loop and nodes are connected sequentially.
=> Adding quickcheck for path graph

rustworkx-core/tests/quickcheck/main.rs, rustworkx-core/tests/quickcheck/star_graph.rs
Checking the number of nodes, edges, no self loops and all the edges pass through the central node.
=> Adding quickcheck for star graph

releasenotes/notes/expose-all-simple-path-multiple-targets-767f818daeeb5a41.yaml, rustworkx/__init__.py, rustworkx/__init__.pyi, rustworkx/rustworkx.pyi, src/connectivity/mod.rs, tests/digraph/test_all_simple_paths.py, tests/graph/test_all_simple_paths.py
This PR enables multiple target being passed as iterable[int] to `rustworkx.all_simple_paths` as mentioned in #1487, the return type stays the same, similar to `networkx`'s implementation.
To ensure backward capabilities, the implementation for single target handling stays the same.
=> Allow multiple targets for rustworkx.all_simple_paths

src/digraph.rs, src/graph.rs, tests/digraph/test_pickle.py, tests/graph/test_pickle.py
Fixes https://github.com/Qiskit/rustworkx/issues/1503. Node contraction removes the contracted nodes but `self.node_removed` wasn't being set. Serialisation works differently depending on the flag. The failure reported in the issue was down to the wrong value of this flag.
=> Fix pickling of graphs with contracted nodes
