appveyor.yml
tools/setup.ps1

This commit adds an appveyor config to run tests in a windows
environment and also build wheels on releases for windows.

Add windows testing with appveyor

---

appveyor.yml

This commit adds the CI automation steps necessary to build wheels for
windows environments.

Add windows wheel builds

---

README.rst

Update readme to include instructions for setting the compiler to nightly rust

Instructions for setting nightly

---

Cargo.toml
setup.py
src/lib.rs

Last minute cleanup prior to pushing a 0.3 release

Prepare for release 0.3

---

Cargo.toml
setup.py

This commit updates the version numbers and package metadata to prepare
for the next release.

Bump versions and prepare for release

---

.travis.yml
MANIFEST.in

This commit adds a coverage job that collects the coverage data from
running the unit tests using grcov and submits the collected data to
coveralls.

Add a coverage job for coveralls

---

README.md
tests/test_edges.py
tests/test_nodes.py

This commit adds a coverage badge to the retworkx README.md file. At the
same time it adds some additional tests to add additional coverage for
some uncovered code paths.

Add coverage badge to README

---

Cargo.toml
setup.py

This commit bumps the package version strings in the Cargo.toml and
setup.py in preparation for a new release.

Bump version strings in preparation for release

---

docs/source/api.rst
src/lib.rs
tests/graph/test_coloring.py

This commit adds a new function for getting the greedy coloring using a
largest first strategy.
This PR is based on top of #75 and will have to be manually rebased after #75 merges (this was needed to get the changes to enable using PyGraph in a function outside of the graph module didn't want to duplicate them here).

Add graph greedy color function

---

.github/dependabot.yml

This commit adds a dependabot.yml file to repo to automate dependency version management

Create a dependabot configuration file

---

src/digraph.rs
tests/test_symmetric.py

This commit adds a new method is_symmetric() to check whether the
graph is symmetric or not.
Co-Authored-By: Kevin Krsulich <kevin@krsulich.net>

Add is_symmetric method to PyDiGraph

---

docs/source/api.rst
src/dag_union.rs
src/digraph.rs
src/lib.rs
src/union.rs
tests/test_nodes.py
tests/test_union.py

- Add weight based union of graphs
- Add merge_nodes
Signed-off-by: Hoss Ajallooiean <katetsu@gmail.com>

Add feature union 

---

src/digraph.rs
src/generators.rs
src/graph.rs

Running clippy from rust nightly has some additional checks which
flagged some small code lint things which could be cleaned up. Mostly
just alternate syntax which is a bit more concise. This commit makes
most of the recommended changes to code from this.

Clean up some small clippy issues

---

CODE_OF_CONDUCT.md

All Qiskit projects point to main CoC file

---

.github/workflows/wheels.yml

https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2

Build universal2 wheels for macOS

---

.github/workflows/main.yml
src/digraph.rs
src/graph.rs
src/iterators.rs
src/lib.rs
src/max_weight_matching.rs

In the recently merged PRs and the release of rust 1.51.0 some clippy
errors have slipped through. This commit fixes those issues so a clippy
run is clean.

Fix clippy issues

---

docs/source/api.rst
releasenotes/notes/floyd-warshall-refactor-423a45c71ab5da63.yaml
retworkx/__init__.py
src/lib.rs
tests/digraph/test_floyd_warshall.py
tests/graph/test_floyd_warshall.py
tests/test_dispatch.py

Closes #351:
* Uses new  `AllPairsPathLengthMapping` return type in `floyd_warshall`
* Support for PyGraph added
* Support for `weight_fn` added
* Parallelization addded

Refactor floyd_warshall

---

MANIFEST.in

Currently, the LICENSE is not included in the source distribution on PyPI. This should fix it.

Add LICENSE to MANIFEST

---

docs/source/api.rst
releasenotes/notes/barbell-graph-generator-5cc9df7148b1a09e.yaml
src/generators.rs
tests/generators/test_barbell.py

Added generator for barbell graphs

---

Cargo.lock
retworkx-core/rustfmt.toml
retworkx-core/src/centrality.rs
retworkx-core/src/connectivity/biconnected.rs
retworkx-core/src/connectivity/chain.rs
retworkx-core/src/dictmap.rs
retworkx-core/src/max_weight_matching.rs
retworkx-core/src/shortest_path/dijkstra.rs
retworkx-core/src/shortest_path/k_shortest_path.rs
retworkx-core/src/traversal/bfs_visit.rs
retworkx-core/src/traversal/dfs_edges.rs
retworkx-core/src/traversal/dfs_visit.rs
retworkx-core/src/traversal/dijkstra_visit.rs

Follow up to #490 
This PR formats retworkx-core with line width of 100 characters. On #490, we accidentally left the line width for the retworkx-core as 80. The PR will fix the inconsistency

Set max line length to 100 characters in retworkx-core

---

docs/source/networkx.rst
retworkx/__init__.py
retworkx/visualization/matplotlib.py
src/connectivity/mod.rs
src/dag_algo/mod.rs
src/iterators.rs
src/layout/mod.rs
src/traversal/mod.rs
src/tree.rs

(cherry picked from commit b50578374346312aa147ff061f07baf676600304)

[Stable] Replace most occurrences of "indexes" with "indices" (#557)

---

retworkx-core/src/centrality.rs
retworkx-core/src/lib.rs

Thanks a lot for your work on this - a very interesting project in Rust!
Reading the docs on , I saw some minor typos and a missing link, see commit.

missing link/minor typos in docs

---

rustworkx-core/src/shortest_path/astar.rs
rustworkx-core/src/shortest_path/bellman_ford.rs
rustworkx-core/src/shortest_path/dijkstra.rs
rustworkx-core/src/shortest_path/k_shortest_path.rs

Partially addresses #587.
I've used tests in `petgraph` as a reference.

Added tests for `shortest_path` algorithms

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

The issue template had the outdated name of the library.
Updated it to the latest version.

updated library name in template

---

src/connectivity/johnson_simple_cycles.rs

We recently merged a new simple_cycles() function in #633 that added an implementation of johnson's algorithm for finding all the simple cycles in a directed graph. In that function we used IndexSet to have a set with O(1) lookup with a deterministic ordering. As part of that we used the default hashing algorithm from the Rust stdlib. This leaves some performance on the table as the stdlib hashing algorithm is slower in order to have proven resistance to HashDoS attacks. Since this is relevant for the internal usage in Johnson's algorithm this commit switches the hasing algorithm to ahash (which is the default hashbrown uses) which offers better performance.

Use ahash with IndexSet in simple_cycles()

---

.github/workflows/wheels.yml

This is a PR into the temp branch originally created by @mtreinish to retrigger just the failing wheels.
The real change associated with this is here: https://github.com/Qiskit/rustworkx/pull/713

[branch: attempt2-fix-wheel-jobs] Add workaround for QEMU Git issue.

---

.zenodo.json

Minor request from https://github.com/openjournals/joss-reviews/issues/3968?notification_referrer_id=NT_kwDOAIWQPrIyNzYyODUyNTUzOjg3NTMyMTQ#issuecomment-1290599714.
We use `rustworkx: A High-Performance Graph Library for Python` as the title for the Zenodo record as well

Use same title as paper for the Zenodo archive

---

paper.bib
paper.md

minor changes in paper

---

rustworkx-core/src/token_swapper.rs

This PR ports the python large partial random test to `rustworkx-core/src/token_swapper.rs`. This test required a core version of `gnm_random_graph` which was recently merged in #818.

Port large random test to core token_swapper

---

src/digraph.rs

Fix typo in add_edge docstring.

---

Cargo.lock

Update README.md - Fix Typo

---

tests/digraph/test_adjacency_matrix.py
tests/graph/test_adjacency_matrix.py

The only change needed was a now-removed alias.  Also fix a typo in a test file's name that otherwise took me literally 6 goes to type even with tab completion.

Fix test suite for Numpy 2

---

releasenotes/notes/collect_runs_core-13073cc7041bc2f5.yaml

A follow up PR to #1210, adding a missing release note.

Add release note for collect_runs

---

releasenotes/notes/fix-layers-stub-66a6e404f55967f0.yaml
rustworkx/rustworkx.pyi

Closes #1340 
There is nothing too deep about this fix, we made a trivial mistake. But made I should add some testing to the annotations correctness themselves

Fix layers type annotations

---

src/digraph.rs

Continuing the quest from #1395

Consolidate docstrings in digraph.rs

---

docs/source/api/generators.rst
src/generators.rs

Another bunch of docstrings reviewed.

Consolidate docstrings in generators.rs

---

rustworkx-core/src/bipartite_coloring.rs
rustworkx/__init__.py
rustworkx/rustworkx.pyi
src/graph.rs
src/graphml.rs
src/iterators.rs
src/matching/mod.rs
src/shortest_path/mod.rs
tests/digraph/test_bipartite.py
tests/digraph/test_nodes.py
tests/digraph/test_strongly_connected.py
tests/graph/test_bipartite.py
tests/graph/test_coloring.py
tests/test_dispatch.py

These are just some typos fixes in docs and test function names.

Fix some typos in docs and test function names

---

rustworkx/__init__.py
rustworkx/visualization/matplotlib.py
tests/digraph/test_node_link_json.py
tests/digraph/test_nodes.py
tests/digraph/test_substitute_node_with_subgraph.py
tests/graph/test_node_link_json.py
tests/graph/test_substitute_node_with_subgraph.py
tests/test_graphml.py
tools/find_stray_release_notes.py

This is just a small refactoring that consolidates string formatting (f-strings).

Consolidate string formatting and converting

---

src/tree.rs

Enhance the documentation and add example for the methods `minimum_spanning_edges` and `minimum_spanning_tree`. Also refactor the code to unpack tuples in loops and use verbose variable names instead of accessing numerated items subsequently.

Enhance docs and unpack tuples in tree.rs

---

rustworkx-core/fuzz/Cargo.toml
rustworkx-core/fuzz/fuzz_targets/test_fuzz_dijkstra.rs

Starting off with a triangle inequality check for Dijkstra's Algorithm.
Thinking about adding one more target for shortest path and then move to other modules.

Adding Dijkstra fuzz target

---

rustworkx-core/src/generators/mod.rs
rustworkx-core/src/generators/random_graph.rs

This pull request adds a random regular graph function in rustworkx-core(this partly resolves - #1391). I will be adding the PyO3 connection and this functionality to rustworkx in a bit. Just wanted to get review on this first.

Adding random regular graph generator for rustworkx-core

---

rustworkx-core/src/centrality.rs

Follow up of #1392
This is nothing too complex, but just like in #593 we missed the parallelization, we also missed that the shortest path function could be a faster one.

Use BFS to compute shortest paths in Closeness Centrality

---

rustworkx-core/fuzz/Cargo.toml
rustworkx-core/fuzz/fuzz_targets/test_fuzz_random_graph.rs

Added a fuzz target for random graph generator with max edges.

Adding Fuzz targets for random graph generator

---

rustworkx/rustworkx.pyi

Improve type annotations for `PyGraph.to_dot` and `PyDiGraph.to_dot`
